//! §260 Phase 3b — opt every app command into the Tauri ACL.
//!
//! Tauri v2 leaves an app's own `#[tauri::command]`s ungated by default: with no
//! AppManifest, `has_app_acl_manifest` is false and any window's JS realm (incl. a
//! loaded plugin) can invoke any command. Registering the commands here flips that
//! global switch — EVERY app command now requires an ACL grant from the calling
//! window's capability. `main`/`file-*` are granted all-but-`plugin_call` in
//! `capabilities/default.json`; `plugin-*` sandbox windows get only `plugin_call`.
//! A command listed here but granted to no window is rejected at runtime, so
//! `tests/acl_lockdown.rs` asserts this list stays identical to `generate_handler!`.
fn main() {
    let app_manifest = tauri_build::AppManifest::new().commands(&[
        "add_context",
        "confirm_quit",
        "copy_file",
        "create_dir",
        "create_snapshot",
        "delete_dir",
        "delete_file",
        "delete_snapshot",
        "detect_pandoc",
        "diff_texts",
        "embed_text",
        "export_binary_file",
        "export_document",
        "export_pandoc",
        "export_pdf",
        "extract_zip",
        "get_backlinks",
        "get_config",
        "get_contexts",
        "get_file_history",
        "get_files_by_tag",
        "get_link_index",
        "get_opened_urls",
        "get_snapshot_diff",
        "get_unlinked_mentions",
        "get_vault_config",
        "get_vault_config_by_path",
        "get_vault_tags",
        "git_ahead_behind",
        "git_branches",
        "git_commit",
        "git_create_branch",
        "git_delete_branch",
        "git_diff_file",
        "git_discard",
        "git_fetch",
        "git_log",
        "git_pull",
        "git_push",
        "git_remotes",
        "git_stage",
        "git_stash_drop",
        "git_stash_list",
        "git_stash_pop",
        "git_stash_save",
        "git_status",
        "git_switch_branch",
        "git_unstage",
        "import_file",
        "index_file",
        "index_status",
        "index_vault",
        "init_vault",
        "keyring_delete_provider_key",
        "keyring_provider_configured",
        "keyring_set_provider_key",
        "list_dir",
        "list_snapshots",
        "llm_cancel",
        "llm_complete",
        "llm_list_models",
        "merge_texts",
        "plugin_add_dev_folder",
        "plugin_call",
        "plugin_fetch_registry",
        "plugin_get_dir",
        "plugin_http_fetch",
        "plugin_install",
        "plugin_list_dev",
        "plugin_list_installed",
        "plugin_prepare_scopes",
        "plugin_read_manifest",
        "plugin_remove_dev_folder",
        "plugin_sandbox_connect",
        "plugin_sandbox_deregister",
        "plugin_sandbox_register",
        "plugin_sandbox_report",
        "plugin_sandbox_send",
        "plugin_storage_list",
        "plugin_storage_read",
        "plugin_storage_remove",
        "plugin_storage_write",
        "plugin_uninstall",
        "read_file",
        "refresh_index",
        "remove_config",
        "remove_context",
        "rename_block_id",
        "rename_file",
        "rename_file_with_links",
        "rename_namespace",
        "rename_tag",
        "resolve_cross_vault_link",
        "resolve_settings",
        "restore_snapshot",
        "run_custom_export",
        "search_files",
        "search_knowledge",
        "set_active_context",
        "set_config",
        "set_vault_config",
        "set_vault_config_by_path",
        "set_vault_root",
        "update_context_alias",
        "update_context_color",
        "update_context_label",
        "update_file_index",
        "update_menu_locale",
        "update_recent_menu",
        "watch_dir",
        "write_binary_file",
        "write_file",
    ]);
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(app_manifest))
        .expect("failed to run tauri-build");
}
