/**
 * Style Dictionary v5 configuration for Baram design tokens.
 *
 * Generates 4 CSS output files:
 *   - src/styles/generated/primitives.css   → @theme { } block for Tailwind 4
 *   - src/styles/generated/semantic-light.css → :root { } block
 *   - src/styles/generated/semantic-dark.css  → [data-theme="dark"] { } block
 *   - src/styles/generated/system-dark.css    → @media (prefers-color-scheme: dark) block
 *
 * Run: npx tsx style-dictionary.config.ts
 */

import StyleDictionary from "style-dictionary";
import type { Config } from "style-dictionary/types";

// ---------------------------------------------------------------------------
// Custom format: @theme { } wrapper for Tailwind 4 primitive tokens
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: async ({ dictionary, options = {}, file }) => {
    const { usesDtcg, formatting } = options;
    const indentation = formatting?.indentation ?? "  ";

    const lines = dictionary.allTokens.map((token) => {
      const value = usesDtcg ? token.$value : token.value;
      return `${indentation}${indentation}--${token.name}: ${value};`;
    });

    return `/* Generated by Style Dictionary — do not edit manually */\n@theme {\n${indentation}/* ${file.destination} */\n${lines.join("\n")}\n}\n`;
  },
});

// ---------------------------------------------------------------------------
// Custom format: @media (prefers-color-scheme: dark) wrapper for system dark mode
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: "css/media-prefers-dark",
  format: async ({ dictionary, options = {} }) => {
    const { usesDtcg } = options;
    const lines = dictionary.allTokens.map((token) => {
      const value = usesDtcg ? token.$value : token.value;
      return `    --${token.name}: ${value};`;
    });

    return (
      "/* AUTO-GENERATED by Style Dictionary — DO NOT EDIT */\n" +
      "@media (prefers-color-scheme: dark) {\n" +
      '  html:not([data-theme="light"], [data-theme="dark"]) {\n' +
      lines.join("\n") +
      "\n" +
      "  }\n" +
      "}\n"
    );
  },
});

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const config: Config = {
  // Tokens use W3C DTCG format ($value, $type)
  usesDtcg: true,

  platforms: {
    // ------------------------------------------------------------------
    // Primitives → @theme { } for Tailwind 4
    // ------------------------------------------------------------------
    "css/primitives": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      source: ["tokens/primitive/**/*.json"],
      files: [
        {
          destination: "primitives.css",
          format: "css/tailwind-theme",
          options: {
            showFileHeader: false,
          },
        },
      ],
    },
  },
};

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

// Primitives: only primitive sources
const sdPrimitives = new StyleDictionary({
  ...config,
  usesDtcg: true,
  source: ["tokens/primitive/**/*.json"],
  platforms: {
    "css/primitives": config.platforms!["css/primitives"],
  },
});

// Semantic light: primitives as base + semantic light as source
const sdLight = new StyleDictionary({
  ...config,
  usesDtcg: true,
  include: ["tokens/primitive/**/*.json"],
  source: ["tokens/semantic/color-light.json"],
  platforms: {
    "css/semantic-light": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "semantic-light.css",
          format: "css/variables",
          filter: (token) => token.filePath.includes("semantic/"),
          options: {
            showFileHeader: false,
            selector: ":root",
            outputReferences: true,
          },
        },
      ],
    },
  },
});

// Semantic dark: primitives as base + semantic dark as source
const sdDark = new StyleDictionary({
  ...config,
  usesDtcg: true,
  include: ["tokens/primitive/**/*.json"],
  source: ["tokens/semantic/color-dark.json"],
  platforms: {
    "css/semantic-dark": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "semantic-dark.css",
          format: "css/variables",
          filter: (token) => token.filePath.includes("semantic/"),
          options: {
            showFileHeader: false,
            selector: '[data-theme="dark"]',
            outputReferences: true,
          },
        },
      ],
    },
  },
});

// System dark: primitives as base + semantic dark as source → @media block
const sdSystemDark = new StyleDictionary({
  ...config,
  usesDtcg: true,
  include: ["tokens/primitive/**/*.json"],
  source: ["tokens/semantic/color-dark.json"],
  platforms: {
    "css/system-dark": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "system-dark.css",
          format: "css/media-prefers-dark",
          filter: (token) => token.filePath.includes("semantic/"),
          options: {
            showFileHeader: false,
            outputReferences: true,
            usesDtcg: true,
          },
        },
      ],
    },
  },
});

await sdPrimitives.buildAllPlatforms();
await sdLight.buildAllPlatforms();
await sdDark.buildAllPlatforms();
await sdSystemDark.buildAllPlatforms();

console.log("\nTokens build complete!");
