/**
 * Style Dictionary v5 configuration for Baram design tokens.
 *
 * Generates 4 CSS output files:
 *   - src/styles/generated/primitives.css   → @theme { } block for Tailwind 4
 *   - src/styles/generated/semantic-light.css → :root { } block
 *   - src/styles/generated/semantic-dark.css  → [data-theme="dark"] { } block
 *   - src/styles/generated/system-dark.css    → @media (prefers-color-scheme: dark) block
 *
 * Run: npx tsx style-dictionary.config.ts
 */

import StyleDictionary from "style-dictionary";
import type { Config } from "style-dictionary/types";

import { THEME_COLOR_KEYS } from "./src/types/theme-color-keys";

// ---------------------------------------------------------------------------
// Custom format: @theme { } wrapper for Tailwind 4 primitive tokens
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: async ({ dictionary, options = {}, file }) => {
    const { usesDtcg, formatting } = options;
    const indentation = formatting?.indentation ?? "  ";

    const lines = dictionary.allTokens.map((token) => {
      const value = usesDtcg ? token.$value : token.value;
      return `${indentation}${indentation}--${token.name}: ${value};`;
    });

    return `/* Generated by Style Dictionary — do not edit manually */\n@theme {\n${indentation}/* ${file.destination} */\n${lines.join("\n")}\n}\n`;
  },
});

// ---------------------------------------------------------------------------
// Custom format: @media (prefers-color-scheme: dark) wrapper for system dark mode
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: "css/media-prefers-dark",
  format: async ({ dictionary, options = {} }) => {
    const { usesDtcg } = options;
    const lines = dictionary.allTokens.map((token) => {
      const value = usesDtcg ? token.$value : token.value;
      return `    --${token.name}: ${value};`;
    });

    return (
      "/* AUTO-GENERATED by Style Dictionary — DO NOT EDIT */\n" +
      "@media (prefers-color-scheme: dark) {\n" +
      '  html:not([data-theme="light"], [data-theme="dark"]) {\n' +
      lines.join("\n") +
      "\n" +
      "  }\n" +
      "}\n"
    );
  },
});

// ---------------------------------------------------------------------------
// Custom format: 편집 가능한 키만 뽑은 TypeScript 팔레트 상수
// ---------------------------------------------------------------------------
// semantic 트리에는 THEME_COLOR_KEYS 보다 많은 토큰이 있다. 테마 에디터가 보여주는
// 것은 그 배열에 있는 것뿐이고, 팔레트는 정확히 그 집합이어야 한다 — 여분 키가
// 섞이면 ThemeColors 타입과 어긋나고, 빠지면 테마 에디터가 빈 색 피커를 그린다.
const EDITABLE = new Set<string>(THEME_COLOR_KEYS.map((k) => k.key));

StyleDictionary.registerFormat({
  name: "ts/theme-palette",
  format: async ({ dictionary, options = {} }) => {
    const { usesDtcg, constName } = options as {
      constName: string;
      usesDtcg?: boolean;
    };
    const byKey = new Map<string, string>();
    for (const token of dictionary.allTokens) {
      const key = `--${token.name}`;
      if (!EDITABLE.has(key)) continue;
      byKey.set(key, String(usesDtcg ? token.$value : token.value));
    }
    const missing = [...EDITABLE].filter((k) => !byKey.has(k));
    if (missing.length > 0) {
      // 조용히 빠진 키는 앱에서 "색이 없는 슬롯"으로만 보인다. 빌드에서 죽인다.
      throw new Error(
        `${constName}: semantic 토큰에 없는 키 ${missing.join(", ")}`,
      );
    }
    const lines = THEME_COLOR_KEYS.map(
      ({ key }) => `  ${JSON.stringify(key)}: ${JSON.stringify(byKey.get(key))},`,
    );
    return (
      "// AUTO-GENERATED by Style Dictionary — DO NOT EDIT\n" +
      "// 출처: tokens/semantic/color-{light,dark}.json · 재생성: npm run tokens:build\n" +
      '\nimport type { ThemeColors } from "../theme-color-keys";\n\n' +
      `export const ${constName}: ThemeColors = {\n${lines.join("\n")}\n};\n`
    );
  },
});

// ---------------------------------------------------------------------------
// Custom format: §365 밀도·모서리 다이얼이 곱하는 스케일의 기준값
// ---------------------------------------------------------------------------
// ‼️ 배열로 내고 값으로 정렬한다 — 객체로 내지 않는다. 토큰 JSON 의 키 "1"·"2" 는
// 정수형이라 JS 가 앞으로 보내고, primitives.css 의 선언 순서가 그 결과다
// (`--space-24` 다음에 `--space-px`). 객체를 내면 소비자가 그 순서를 스케일
// 순서로 읽는다.
StyleDictionary.registerFormat({
  name: "ts/scale",
  format: async ({ dictionary, options = {} }) => {
    const { usesDtcg } = options;
    const scale = (group: "radius" | "space"): string =>
      dictionary.allTokens
        .filter((token) => token.path[0] === group)
        .map((token) => {
          const raw = String(usesDtcg ? token.$value : token.value);
          const match = /^(\d+)px$/u.exec(raw);
          // 정수 px 가 아니면 다이얼이 곱할 수 없다. 조용히 빼면 그 토큰 하나만
          // 다이얼을 따라오지 않는다 — 빌드에서 죽인다.
          if (match === null) {
            throw new Error(`ts/scale: --${token.name} is ${raw}, not integer px`);
          }
          return [`--${token.name}`, Number(match[1])] as const;
        })
        .sort((a, b) => a[1] - b[1])
        .map(([name, px]) => `  [${JSON.stringify(name)}, ${px}],`)
        .join("\n");
    const type = "readonly (readonly [name: string, px: number])[]";
    return (
      "// AUTO-GENERATED by Style Dictionary — DO NOT EDIT\n" +
      "// 출처: tokens/primitive/spacing.json · 재생성: npm run tokens:build\n\n" +
      `export const SPACE_SCALE: ${type} = [\n${scale("space")}\n];\n\n` +
      `export const RADIUS_SCALE: ${type} = [\n${scale("radius")}\n];\n`
    );
  },
});

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const config: Config = {
  // Tokens use W3C DTCG format ($value, $type)
  usesDtcg: true,

  platforms: {
    // ------------------------------------------------------------------
    // Primitives → @theme { } for Tailwind 4
    // ------------------------------------------------------------------
    "css/primitives": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      source: ["tokens/primitive/**/*.json"],
      files: [
        {
          destination: "primitives.css",
          format: "css/tailwind-theme",
          options: {
            showFileHeader: false,
          },
        },
      ],
    },
  },
};

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

// Primitives: only primitive sources
const sdPrimitives = new StyleDictionary({
  ...config,
  usesDtcg: true,
  source: ["tokens/primitive/**/*.json"],
  platforms: {
    "css/primitives": config.platforms!["css/primitives"],
    "ts/scale": {
      transformGroup: "css",
      buildPath: "src/types/generated/",
      files: [
        {
          destination: "scale.ts",
          format: "ts/scale",
          options: { showFileHeader: false },
        },
      ],
    },
  },
});

// Semantic light: primitives as base + semantic light as source
const sdLight = new StyleDictionary({
  ...config,
  usesDtcg: true,
  include: ["tokens/primitive/**/*.json"],
  source: ["tokens/semantic/color-light.json"],
  platforms: {
    "css/semantic-light": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "semantic-light.css",
          format: "css/variables",
          filter: (token) => token.filePath.includes("semantic/"),
          options: {
            showFileHeader: false,
            selector: ":root",
            outputReferences: true,
          },
        },
      ],
    },
    "ts/palette-light": {
      transformGroup: "css",
      buildPath: "src/types/generated/",
      files: [
        {
          destination: "palette-light.ts",
          format: "ts/theme-palette",
          filter: (token) => token.filePath.includes("semantic/"),
          options: { constName: "DEFAULT_LIGHT_PALETTE", showFileHeader: false },
        },
      ],
    },
  },
});

// Semantic dark: primitives as base + semantic dark as source
const sdDark = new StyleDictionary({
  ...config,
  usesDtcg: true,
  include: ["tokens/primitive/**/*.json"],
  source: ["tokens/semantic/color-dark.json"],
  platforms: {
    "css/semantic-dark": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "semantic-dark.css",
          format: "css/variables",
          filter: (token) => token.filePath.includes("semantic/"),
          options: {
            showFileHeader: false,
            selector: '[data-theme="dark"]',
            outputReferences: true,
          },
        },
      ],
    },
    "ts/palette-dark": {
      transformGroup: "css",
      buildPath: "src/types/generated/",
      files: [
        {
          destination: "palette-dark.ts",
          format: "ts/theme-palette",
          filter: (token) => token.filePath.includes("semantic/"),
          options: { constName: "DEFAULT_DARK_PALETTE", showFileHeader: false },
        },
      ],
    },
  },
});

// System dark: primitives as base + semantic dark as source → @media block
const sdSystemDark = new StyleDictionary({
  ...config,
  usesDtcg: true,
  include: ["tokens/primitive/**/*.json"],
  source: ["tokens/semantic/color-dark.json"],
  platforms: {
    "css/system-dark": {
      transformGroup: "css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "system-dark.css",
          format: "css/media-prefers-dark",
          filter: (token) => token.filePath.includes("semantic/"),
          options: {
            showFileHeader: false,
            outputReferences: true,
            usesDtcg: true,
          },
        },
      ],
    },
  },
});

await sdPrimitives.buildAllPlatforms();
await sdLight.buildAllPlatforms();
await sdDark.buildAllPlatforms();
await sdSystemDark.buildAllPlatforms();

console.log("\nTokens build complete!");
