//! §260 — guardrail for the plugin trust boundary: a permission must not be able to
//! reach a `plugin-*` sandbox webview without a named test failing.
//!
//! Baram runs sandboxed plugins in per-plugin `WebviewWindow`s labelled `plugin-<id>`;
//! the host realm is `main` plus `file-*`. The canonical command set comes from the
//! `generate_handler!` list in `src/lib.rs`, and this file asserts that `build.rs`'s
//! `AppManifest`, the capability files, and the app ACL manifest all agree with it.
//!
//! ‼️ Everything keys on **which webviews a capability applies to**, never on the file it
//! lives in. Until 2026-08-09 five tests read exactly two hardcoded paths, so a third
//! file granting anything to `plugin-*` was invisible. Proven, not reasoned:
//! `capabilities/zz-leak.json` with `core:window:allow-close` on `"windows":
//! ["plugin-*"]` left all 7 tests green — including the one that asserts, in so many
//! words, that "the sandbox tier must hold no window permission at all".
//!
//! ## Every input that can widen the boundary
//!
//! Read out of the crate sources, not assumed (tauri-utils 2.9.3, tauri-build 2.6.3,
//! tauri-macros 2.6.3, tauri-codegen 2.6.3, tauri 2.11.5). Each line is an input; each
//! has a test below, because a review found that four of them were unguarded after the
//! first rewrite:
//!
//! 1. **`capabilities/**/*`** — `parse_capabilities` (tauri-build `acl.rs:428`) globs
//!    recursively. Its schema filter tests only the **immediate parent**
//!    (tauri-utils `acl/build.rs:217`), so `capabilities/schemas/desktop/x.json` IS
//!    applied; pruning the whole `schemas` subtree would audit less than tauri does.
//! 2. **Extensions** — `CAPABILITY_FILE_EXTENSIONS` is `["json", "toml"]` plus `"json5"`
//!    under `config-json5` (`acl/build.rs:42`). **`toml` is not feature-gated**, so a
//!    `.toml` capability is live today. Refused here rather than parsed.
//! 3. **`app.security.capabilities`** — `get_capabilities` (tauri-utils `acl/mod.rs:353`):
//!    empty ⇒ every parsed file is live; non-empty ⇒ only the listed ones, where
//!    `Reference(id)` pulls a file in and `Inlined` lives in the config alone.
//! 4. **Other config files** — `read_from` merges `tauri.<platform>.conf.json[5]` over
//!    `tauri.conf.json` by RFC-7396 patch (`config/parse.rs:183`), and the CLI merges any
//!    `--config` file: this repo's release workflow passes `tauri.release.conf.json`. So
//!    input 3 has several possible homes, including one that only release builds see.
//! 5. **`generate_context!(capabilities = […])`** — a `Meta::NameValue` the macro accepts
//!    (tauri-macros `context.rs:66`); `get_capabilities` appends those files
//!    unconditionally, AFTER the selector, from any path, and tauri-build's
//!    `validate_capabilities` never sees them (`acl/mod.rs:396-412`).
//! 6. **`permissions/**/*`** — tauri-build feeds the app manifest from the autogenerated
//!    directory AND the whole tree (`acl.rs:~317`), and `get_permissions` resolves a
//!    `[[set]]` BEFORE a permission of the same name (tauri-utils `resolved.rs:358` vs
//!    `:360`). So a hand-written set can redefine what an already-granted permission id
//!    expands to, with every capability file byte-identical.
//! 7. **`deny-*` entries** — `RuntimeAuthority` treats the mere PRESENCE of a denial as
//!    denial for every window: `denied_commands.get(cmd).map(|r| r.iter().any(..)).is_some()`
//!    discards the `any` result (tauri `ipc/authority.rs:446-452`).
//! 8. **`remote` / `local`** — they become the `ExecutionContext` half of the authority
//!    check (`resolved.rs:218-226`), so `remote.urls` admits a remote origin and
//!    `local: false` makes a capability tauri does not apply to local content.
//!
//! Deliberately not modelled: `platforms`. A capability limited to `["linux"]` is still a
//! grant on Linux, and filtering by the host target would hide it from a macOS developer,
//! so every capability is audited on every platform.
//!
//! Two things need no guard because tauri already makes them hard errors: duplicate
//! identifiers across capability files (`CapabilityAlreadyExists`) and permissions naming
//! no known command (`validate_capabilities`).
//!
//! ## Companion guard, elsewhere
//!
//! The sandbox's three IPC permissions are pinned here, but its real authority is what the
//! `plugin_call` broker will do with a request — the `PluginOp` → `CapabilityRequirement`
//! mapping in `src/plugin/authorizer.rs`, guarded there by
//! `required_capability_mapping_is_exhaustive_and_not_cross_wired`. A new op gated at
//! `CapabilityRequirement::None` widens the sandbox without touching any permission string
//! this file can see. `the_broker_capability_mapping_guard_still_exists` below fails if
//! that companion test is deleted.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(rel: &str) -> String {
    let p = manifest_dir().join(rel);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()))
}

/// Rust source with comments and string literals blanked, for the drift guards that scan
/// code for a call that must (not) be there.
///
/// Both comment forms are removed, and string bodies with them. A raw `contains` over
/// source has two failure modes and this closes both: a future comment that merely NAMES
/// the thing becomes a spurious failure (the defect a guard in `src/logging` shipped
/// with), and a `//` inside a string literal truncates the rest of a line, hiding a real
/// call after it.
fn code_only(rel: &str) -> String {
    let src = read(rel);
    let mut out = String::with_capacity(src.len());
    let mut chars = src.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '/' if chars.peek() == Some(&'/') => {
                for c in chars.by_ref() {
                    if c == '\n' {
                        out.push('\n');
                        break;
                    }
                }
            }
            '/' if chars.peek() == Some(&'*') => {
                chars.next();
                let mut prev = '\0';
                for c in chars.by_ref() {
                    if prev == '*' && c == '/' {
                        break;
                    }
                    if c == '\n' {
                        out.push('\n');
                    }
                    prev = c;
                }
            }
            '"' => {
                out.push('"');
                while let Some(c) = chars.next() {
                    match c {
                        '\\' => {
                            chars.next();
                        }
                        '"' => break,
                        '\n' => out.push('\n'),
                        _ => {}
                    }
                }
                out.push('"');
            }
            c => out.push(c),
        }
    }
    out
}

/// Normalize a command/permission stem so `-` and `_` compare equal. Command
/// names are snake_case; the generated permission id is `allow-<snake>`, but
/// normalizing makes the test robust if tauri-build ever kebab-cases the stem.
fn norm(s: &str) -> String {
    s.trim().replace('-', "_")
}

/// Commands registered in `generate_handler![ ... ]` in src/lib.rs, with any
/// `module::` path prefix stripped. Authoritative registered set.
fn generate_handler_commands() -> BTreeSet<String> {
    let src = read("src/lib.rs");
    let start = src
        .find("generate_handler![")
        .expect("generate_handler! not found");
    let rest = &src[start + "generate_handler![".len()..];
    let end = rest
        .find("])")
        .expect("generate_handler! close `])` not found");
    rest[..end]
        .split(',')
        .map(str::trim)
        .filter(|t| !t.is_empty())
        .map(|t| norm(t.rsplit("::").next().unwrap()))
        .collect()
}

/// Command list passed to `AppManifest::new().commands(&[ ... ])` in build.rs.
fn build_manifest_commands() -> BTreeSet<String> {
    let src = read("build.rs");
    let start = src
        .find(".commands(&[")
        .expect(".commands(&[ not found in build.rs");
    let rest = &src[start + ".commands(&[".len()..];
    let end = rest.find("])").expect(".commands close `])` not found");
    rest[..end]
        .split(',')
        .map(|t| t.trim().trim_matches('"').trim())
        .filter(|t| !t.is_empty())
        .map(norm)
        .collect()
}

/// The window/webview globs the host realm owns. `file-*` is the single-file viewer.
const HOST_TARGETS: [&str; 2] = ["main", "file-*"];
/// The globs the sandbox owns — one per-plugin webview window, label `plugin-<id>`.
const SANDBOX_TARGETS: [&str; 1] = ["plugin-*"];

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Tier {
    Host,
    Sandbox,
}

/// One capability as tauri will apply it, wherever it was declared.
#[derive(Clone, Debug)]
struct Capability {
    /// Where it came from, for failure messages: a path, or the config.
    source: String,
    identifier: String,
    /// `windows` ∪ `webviews` — the two axes tauri ORs at invoke time.
    targets: BTreeSet<String>,
    /// Permission identifiers, `norm`-alized. Colon-prefixed plugin/core
    /// permissions are kept whole; bare grants keep their `allow_` / `deny_` stem.
    permissions: BTreeSet<String>,
    /// The same identifiers exactly as written. `norm` maps `-` to `_` so the tier
    /// comparisons are stable, but the ACL manifests are keyed on the original kebab ids,
    /// so the expansion below needs them un-normalized. Kept here rather than re-read from
    /// `source`, which is not always a path — an inline config capability's source names a
    /// JSON pointer, and reading it as a file would panic.
    raw_permissions: Vec<String>,
    /// `local` as written — `None` when absent (tauri defaults it to `true`).
    local: Option<bool>,
    /// `remote.urls` as written; non-empty means non-local origins are admitted.
    remote_urls: Vec<String>,
}

/// Every capability file, discovered the way `parse_capabilities` does.
///
/// The schema filter mirrors tauri exactly: a FILE is skipped when its immediate parent
/// directory is `schemas`, and every directory is still descended into. Pruning the whole
/// subtree instead — the first version of this rewrite did — leaves
/// `capabilities/schemas/desktop/x.json` applied by tauri and audited by nobody. For a
/// discovery function, seeing less than tauri is the unsafe direction.
///
/// `.toml` / `.json5` are refused rather than skipped, because tauri parses `.toml` with
/// no cargo feature and a JSON-only reader would audit nothing. Extensions that are not a
/// capability format at all (`.DS_Store`, notes) are ignored, exactly as tauri ignores
/// them; a `.json` file that is not a capability is a hard error in both (tauri fails the
/// build in `CapabilityFile::load`, this file panics while parsing).
fn capability_files() -> Vec<PathBuf> {
    let dir = manifest_dir().join("capabilities");
    let mut files = Vec::new();
    let mut stack = vec![dir];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d)
            .unwrap_or_else(|e| panic!("read {}: {e}", d.display()))
            .flatten()
        {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            let in_schema_dir = path
                .parent()
                .and_then(|p| p.file_name())
                .is_some_and(|n| n == "schemas");
            if in_schema_dir {
                continue;
            }
            match path.extension().and_then(|x| x.to_str()) {
                Some("json") => files.push(path),
                Some(other @ ("toml" | "json5")) => panic!(
                    "{} is a `{other}` capability. tauri's CAPABILITY_FILE_EXTENSIONS accepts \
                     it (`toml` needs no cargo feature), so it is a LIVE grant, but this \
                     lockdown only parses JSON and would audit nothing. Convert it to JSON, \
                     or teach this file that format.",
                    path.display()
                ),
                _ => {}
            }
        }
    }
    files.sort();
    files
}

/// Build one `Capability` from its JSON object.
fn capability_from_json(json: &serde_json::Value, source: &str) -> Capability {
    let identifier = json["identifier"]
        .as_str()
        .unwrap_or_else(|| panic!("{source}: capability has no `identifier`: {json}"))
        .to_string();

    let globs = |key: &str| -> Vec<String> {
        json[key]
            .as_array()
            .map(|a| a.as_slice())
            .unwrap_or_default()
            .iter()
            .filter_map(|w| w.as_str())
            .map(str::to_string)
            .collect()
    };
    let targets: BTreeSet<String> = globs("windows")
        .into_iter()
        .chain(globs("webviews"))
        .collect();
    assert!(
        !targets.is_empty(),
        "{source}: capability `{identifier}` declares neither `windows` nor `webviews`, so \
         tauri matches it to nothing (`ipc/authority.rs`: both `any()` calls are false on an \
         empty list). Silently inert config is the failure mode this file guards; declare a \
         target or delete it."
    );

    let raw_permissions: Vec<String> = json["permissions"]
        .as_array()
        .map(|a| a.as_slice())
        .unwrap_or_default()
        .iter()
        // A permission entry is a bare string OR an object with an `identifier`
        // (`PermissionEntry::ExtendedPermission`, used to attach a scope). Reading only
        // strings would let `{"identifier": "log:default"}` through.
        .filter_map(|p| {
            p.as_str()
                .or_else(|| p.get("identifier").and_then(|i| i.as_str()))
        })
        .map(str::to_string)
        .collect();
    let permissions: BTreeSet<String> = raw_permissions.iter().map(|p| norm(p)).collect();

    Capability {
        source: source.to_string(),
        identifier,
        targets,
        permissions,
        raw_permissions,
        local: json["local"].as_bool(),
        remote_urls: json["remote"]["urls"]
            .as_array()
            .map(|a| a.as_slice())
            .unwrap_or_default()
            .iter()
            .filter_map(|u| u.as_str())
            .map(str::to_string)
            .collect(),
    }
}

/// One file may hold a single capability, a bare array of them, or
/// `{"capabilities": [...]}` — tauri's `CapabilityFile` accepts all three, so reading
/// `json["permissions"]` alone would panic on two of them, and a panicking test never
/// gets to inspect the grants it exists to inspect.
fn capabilities_in_file(path: &Path) -> Vec<Capability> {
    let source = path
        .strip_prefix(manifest_dir())
        .unwrap_or(path)
        .display()
        .to_string();
    let json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).expect("read capability"))
            .unwrap_or_else(|e| panic!("{source}: parse capability: {e}"));

    let objects: Vec<&serde_json::Value> = if let Some(list) = json.as_array() {
        list.iter().collect()
    } else if let Some(list) = json.get("capabilities").and_then(|c| c.as_array()) {
        list.iter().collect()
    } else {
        vec![&json]
    };
    objects
        .into_iter()
        .map(|o| capability_from_json(o, &source))
        .collect()
}

/// `app.security.capabilities` from `tauri.conf.json`. Empty (or absent) means every
/// parsed file is live; see input 3 in the module header.
fn config_capability_entries() -> Vec<serde_json::Value> {
    let json: serde_json::Value =
        serde_json::from_str(&read("tauri.conf.json")).expect("parse tauri.conf.json");
    json["app"]["security"]["capabilities"]
        .as_array()
        .cloned()
        .unwrap_or_default()
}

/// Every capability that will actually be applied, from every place tauri looks.
///
/// Cached: the tests below call this a dozen times and it walks the tree and parses every
/// file each time. Cheap at this size, but the cache also keeps one panic message for an
/// unclassifiable capability instead of one per caller.
fn live_capabilities() -> &'static [Capability] {
    static CACHE: OnceLock<Vec<Capability>> = OnceLock::new();
    CACHE.get_or_init(|| {
        let from_files: Vec<Capability> = capability_files()
            .iter()
            .flat_map(|p| capabilities_in_file(p))
            .collect();

        let entries = config_capability_entries();
        if entries.is_empty() {
            return from_files;
        }

        let by_id: BTreeMap<&str, &Capability> = from_files
            .iter()
            .map(|c| (c.identifier.as_str(), c))
            .collect();
        entries
            .iter()
            .map(|entry| match entry.as_str() {
                Some(id) => (*by_id.get(id).unwrap_or_else(|| {
                    panic!(
                        "tauri.conf.json references capability `{id}`, which no file under \
                         capabilities/ defines"
                    )
                }))
                .clone(),
                None => capability_from_json(entry, "tauri.conf.json#app.security.capabilities"),
            })
            .collect()
    })
}

/// Which tier a capability applies to, by its target globs — `None` if it reaches
/// somewhere this lockdown has no model for (a new glob, a `*`, or a mix of tiers).
fn tier_of(capability: &Capability) -> Option<Tier> {
    let all_in = |known: &[&str]| {
        capability
            .targets
            .iter()
            .all(|t| known.contains(&t.as_str()))
    };
    if all_in(&HOST_TARGETS) {
        Some(Tier::Host)
    } else if all_in(&SANDBOX_TARGETS) {
        Some(Tier::Sandbox)
    } else {
        None
    }
}

fn unclassifiable(capability: &Capability) -> String {
    format!(
        "{} declares capability `{}` on {:?}, which is neither the host tier {:?} nor the \
         sandbox tier {:?} — a `*`, a new window label, or one capability spanning both. \
         This lockdown cannot say who it grants to. Split it per tier, or extend the tier \
         constants deliberately.",
        capability.source, capability.identifier, capability.targets, HOST_TARGETS, SANDBOX_TARGETS,
    )
}

/// Union of the permissions every capability in `tier` grants.
///
/// Panics on an unclassifiable capability rather than dropping it: dropping would make
/// every aggregate assertion below silently blind to exactly the file that needs
/// auditing. `every_capability_targets_exactly_one_known_tier` reports it on its own.
fn permissions_of(tier: Tier) -> BTreeSet<String> {
    let mut perms = BTreeSet::new();
    for capability in live_capabilities() {
        match tier_of(capability) {
            Some(t) if t == tier => perms.extend(capability.permissions.iter().cloned()),
            Some(_) => {}
            None => panic!("{}", unclassifiable(capability)),
        }
    }
    perms
}

/// Bare app-command grants within a permission set: `allow_*` entries with no plugin `:`
/// prefix (core/plugin perms like `core:window:allow_create` are excluded by the `:`
/// test). `deny_*` is not an allowance and is guarded separately by
/// `no_capability_denies_a_command`.
fn app_commands(permissions: &BTreeSet<String>) -> BTreeSet<String> {
    permissions
        .iter()
        .filter(|p| !p.contains(':'))
        // `strip_prefix`, not `trim_start_matches`: the latter strips a repeated prefix,
        // so `allow_allow_x` would become `x`.
        .filter_map(|p| p.strip_prefix("allow_"))
        .map(str::to_string)
        .collect()
}

#[test]
fn app_manifest_matches_registered_commands() {
    let registered = generate_handler_commands();
    let manifest = build_manifest_commands();
    assert_eq!(
        registered,
        manifest,
        "build.rs AppManifest::commands must list exactly the generate_handler! commands.\n\
         missing from build.rs: {:?}\nextra in build.rs: {:?}",
        registered.difference(&manifest).collect::<Vec<_>>(),
        manifest.difference(&registered).collect::<Vec<_>>(),
    );
}

/// Non-vacuity anchor for every aggregate assertion in this file.
///
/// All of them are "the union over tier T grants exactly X". A discovery that finds
/// nothing makes an empty union, and several of those assertions would then be arguing
/// about nothing. This one fails first, and names what went missing.
#[test]
fn capability_discovery_sees_both_known_tiers() {
    let live = live_capabilities();
    let ids: BTreeSet<&str> = live.iter().map(|c| c.identifier.as_str()).collect();
    for required in ["default", "plugin-sandbox"] {
        assert!(
            ids.contains(required),
            "capability `{required}` is not live. Either its file moved or was renamed, or \
             `app.security.capabilities` in tauri.conf.json now lists a subset that leaves it \
             out (a non-empty list silences every file it does not name). Live: {ids:?}"
        );
    }
    for tier in [Tier::Host, Tier::Sandbox] {
        assert!(
            live.iter().any(|c| tier_of(c) == Some(tier)),
            "no live capability applies to the {tier:?} tier; the per-tier assertions below \
             would be comparing empty sets"
        );
    }
}

/// Input 1 — everything above walks `capabilities/` because that is tauri-build's default
/// (`parse_capabilities("./capabilities/**/*")`, taken when `Attributes` carries no
/// `capabilities_path_pattern`).
///
/// Overriding the pattern would point tauri at a different tree while this file kept
/// auditing the old one — the whole suite green about files nobody applies. That is the
/// one assumption the discovery cannot detect from its own results, so it is asserted
/// against the source instead.
#[test]
fn capability_discovery_uses_the_same_root_as_tauri_build() {
    let build_rs = code_only("build.rs");
    assert!(
        !build_rs.contains("capabilities_path_pattern"),
        "build.rs overrides the capability path pattern, so `capabilities/` is no longer \
         where tauri looks. Point `capability_files` at the same tree, or this lockdown \
         audits files that are not applied and misses the ones that are."
    );
}

/// Input 4 — `tauri.conf.json` is not the only config. `read_from` merges
/// `tauri.<platform>.conf.json[5]` over it by RFC-7396 patch (tauri-utils
/// `config/parse.rs:183`), and the CLI merges whatever `--config` names — this repo's
/// release workflow passes `src-tauri/tauri.release.conf.json`, which is how that file was
/// found: by this test failing on its first run.
///
/// So `app.security.capabilities` has several possible homes and `config_capability_entries`
/// reads one. A selector added to any of the others would reselect the live capability set
/// for those builds — the release build, in the `--config` case — while
/// `capability_discovery_sees_both_known_tiers` kept passing, because the list IT reads is
/// still absent.
///
/// Rather than model tauri's merge, this asserts the property that makes reading one file
/// correct: **only `tauri.conf.json` declares the selector**. That covers platform configs,
/// `--config` configs and future variants alike, instead of enumerating names — an
/// enumeration would admit the next one by default.
#[test]
fn only_the_canonical_config_declares_the_capability_selector() {
    let dir = manifest_dir();
    let mut checked_canonical = false;
    for entry in std::fs::read_dir(&dir).expect("read src-tauri/").flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        let is_json_config = name.starts_with("tauri") && name.contains(".conf.json");
        // A TOML config would need a parser this test does not have, and this repo has no
        // TOML config; refuse one rather than skip it, as with `.toml` capabilities.
        assert!(
            !(name.starts_with("Tauri") && name.ends_with(".toml")),
            "{name} is a TOML tauri config. It can carry `app.security.capabilities` and this \
             guard only parses JSON. Convert it, or teach this file that format."
        );
        if !is_json_config {
            continue;
        }
        if name == "tauri.conf.json" {
            checked_canonical = true;
            continue;
        }
        let json: serde_json::Value =
            serde_json::from_str(&read(&name)).unwrap_or_else(|e| panic!("parse {name}: {e}"));
        assert!(
            json["app"]["security"]["capabilities"].is_null(),
            "{name} declares app.security.capabilities. It is merged over tauri.conf.json \
             (platform configs automatically, `--config` files when the CLI is given one — \
             the release workflow passes tauri.release.conf.json), so it reselects the live \
             capability set for those builds while this lockdown reads only tauri.conf.json. \
             Move the setting, or teach `config_capability_entries` to merge this file."
        );
    }
    // Non-vacuity: a scan that matched nothing would pass while auditing nothing. The
    // canonical config is the one file guaranteed to be there.
    assert!(
        checked_canonical,
        "the scan never saw tauri.conf.json in {}, so it is not looking where the configs are",
        dir.display()
    );
}

/// Input 5 — `generate_context!(capabilities = ["…"])` loads capability files from ANY
/// path (tauri-macros `context.rs:66`), and `get_capabilities` appends them
/// unconditionally, after the config selector, where tauri-build's `validate_capabilities`
/// never sees them. A capability injected that way is invisible to every other test here.
///
/// Asserted POSITIVELY — the call must be the bare form, and there must be exactly one of
/// it. An absence check would have to guess how the argument is spelled.
#[test]
fn generate_context_injects_no_additional_capabilities() {
    let lib_rs = code_only("src/lib.rs");
    let calls = lib_rs.matches("generate_context!").count();
    assert_eq!(
        calls, 1,
        "expected exactly one `generate_context!` in src/lib.rs, found {calls}; this guard \
         inspects the single call site"
    );
    assert!(
        lib_rs.contains("generate_context!()"),
        "`generate_context!` in src/lib.rs is not the bare form. Its `capabilities = [...]` \
         argument injects capability files from any path, bypassing both `capabilities/` and \
         `app.security.capabilities`, and nothing else in this file would see them. Put the \
         capability under capabilities/ instead."
    );
}

/// Input 6 — the app ACL manifest is fed from `permissions/autogenerated/*` AND from
/// `permissions/**/*` (tauri-build `acl.rs`), and `get_permissions` resolves a `[[set]]`
/// before a permission of the same name (tauri-utils `resolved.rs:358` vs `:360`).
///
/// So committing `permissions/anything.toml` with
///
/// ```toml
/// [[set]]
/// identifier = "allow-plugin-sandbox-report"
/// permissions = ["allow-plugin-sandbox-report", "allow-read-file"]
/// ```
///
/// redefines what an already-granted permission id expands to. `plugin-sandbox.json` stays
/// byte-identical, `sandbox_tier_grants_exactly_its_allowlist` still sees exactly its three
/// strings, and a sandboxed plugin gains `read_file`. `permissions/autogenerated` is
/// gitignored; `permissions/` is not, so the file is committable.
///
/// This is why every other test here compares permission *identifiers*: the identifiers are
/// only meaningful while nothing redefines them.
#[test]
fn the_app_acl_manifest_has_no_handwritten_permissions() {
    let root = manifest_dir().join("permissions");
    assert!(
        root.is_dir(),
        "{} is missing; tauri-build writes the autogenerated app permissions there and this \
         guard has nothing to check",
        root.display()
    );

    let mut seen = 0usize;
    let mut stack = vec![root.clone()];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d)
            .unwrap_or_else(|e| panic!("read {}: {e}", d.display()))
            .flatten()
        {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            let rel = path.strip_prefix(&root).unwrap_or(&path).to_path_buf();
            assert!(
                rel.starts_with("autogenerated"),
                "{} is a hand-written app permission file. Everything under permissions/ \
                 joins the app ACL manifest, and a `[[set]]` there can redefine a permission \
                 id that every capability file already grants — widening a tier while no \
                 capability file changes. Only permissions/autogenerated/ (written by \
                 tauri-build) belongs here.",
                path.display()
            );
            let body = std::fs::read_to_string(&path).expect("read permission file");
            assert!(
                !body.contains("[[set]]"),
                "{} declares a permission [[set]]. `get_permissions` resolves a set BEFORE a \
                 permission of the same name, so a set can shadow an autogenerated \
                 `allow-<command>` and expand it to other commands.",
                path.display()
            );
            seen += 1;
        }
    }
    // Non-vacuity: one command yields one autogenerated file, and `generate_handler!`
    // registers over a hundred. A walk that found a handful is broken, not clean.
    let registered = generate_handler_commands().len();
    assert!(
        seen >= registered,
        "walked only {seen} permission files for {registered} registered commands — the walk \
         is not seeing the tree it is meant to audit"
    );

    // …and the same override hazard as the capability pattern: a custom permissions glob
    // would point tauri at a tree this test does not walk.
    assert!(
        !code_only("build.rs").contains("permissions_path_pattern"),
        "build.rs overrides the app permissions path pattern; point this guard at the same \
         tree or it audits the wrong one"
    );
}

#[test]
fn every_capability_targets_exactly_one_known_tier() {
    for capability in live_capabilities() {
        assert!(
            tier_of(capability).is_some(),
            "{}",
            unclassifiable(capability)
        );
    }
}

#[test]
fn the_two_tiers_apply_to_disjoint_window_sets() {
    let mut host: BTreeSet<String> = BTreeSet::new();
    let mut sandbox: BTreeSet<String> = BTreeSet::new();
    for capability in live_capabilities() {
        match tier_of(capability) {
            Some(Tier::Host) => host.extend(capability.targets.iter().cloned()),
            Some(Tier::Sandbox) => sandbox.extend(capability.targets.iter().cloned()),
            // Reported by `every_capability_targets_exactly_one_known_tier`.
            None => {}
        }
    }
    // Both directions are named: dropping `file-*` from the host capability breaks the
    // §89 single-file viewer, and a message about over-granting would describe the
    // opposite problem. No `is_disjoint` check follows — with both sets pinned to
    // disjoint constants it could never fail, and the real protection against a `*` is
    // `tier_of` returning `None`.
    let expected_host: BTreeSet<String> = HOST_TARGETS.iter().map(|s| s.to_string()).collect();
    assert_eq!(
        host,
        expected_host,
        "host capabilities must apply to exactly the host windows.\n\
         unexpected (sandbox reachable from a host capability?): {:?}\nmissing: {:?}",
        host.difference(&expected_host).collect::<Vec<_>>(),
        expected_host.difference(&host).collect::<Vec<_>>(),
    );
    let expected_sandbox: BTreeSet<String> =
        SANDBOX_TARGETS.iter().map(|s| s.to_string()).collect();
    assert_eq!(
        sandbox,
        expected_sandbox,
        "sandbox capabilities must apply to exactly the sandbox windows.\n\
         unexpected: {:?}\nmissing: {:?}",
        sandbox.difference(&expected_sandbox).collect::<Vec<_>>(),
        expected_sandbox.difference(&sandbox).collect::<Vec<_>>(),
    );
}

#[test]
fn sandbox_tier_grants_exactly_its_allowlist() {
    // Guard the WHOLE permission set of the sandbox tier, not just its bare app-command
    // (allow-*) grants. A colon-prefixed core/plugin permission — e.g.
    // `core:webview:allow-create-webview-window`, `core:default`, or a plugin scope like
    // `fs:allow-read` — would be a boundary leak, exactly the class this lockdown exists
    // to prevent, yet a bare-`allow-*` check would miss it.
    //
    // §260 Phase 3c-2a — `core:event:*` is WITHHELD and must never come back.
    // Tauri delivers a broadcast event to any JS listener registered with the
    // default `EventTarget::Any`, and `emit_to`/`emit_filter` cannot withhold it
    // (`match_any_or_filter`, tauri/src/event/listener.rs). So `allow-listen` on a
    // plugin-* window = a sandboxed plugin with ZERO capabilities can eavesdrop on
    // `llm:token`, `file:changed`, etc. The sandbox transport therefore uses
    // per-webview IPC instead: `plugin_sandbox_connect` (inbound ipc::Channel) +
    // `plugin_sandbox_report` (outbound, caller-identified), plus the broker
    // `plugin_call`.
    //
    // This asserts the GRANTED set, which is not identical to the REACHABLE set:
    // tauri hardcodes an ACL bypass for `FETCH_CHANNEL_DATA_COMMAND`
    // (`plugin:__TAURI_CHANNEL__|fetch`, `webview/mod.rs`, marked `TODO: Remove
    // this special check in v3`), so every webview can invoke that one regardless
    // of its capability. It is how a >8 KiB `ipc::Channel` frame is delivered; see
    // `SandboxChannels::send`, which warns in dev if our frames ever get that big.
    // `norm()` maps `-`->`_`, so kebab permission ids compare stably.
    let granted = permissions_of(Tier::Sandbox);
    let expected: BTreeSet<String> = [
        "allow_plugin_call",
        "allow_plugin_sandbox_connect",
        "allow_plugin_sandbox_report",
    ]
    .into_iter()
    .map(str::to_string)
    .collect();
    assert_eq!(
        granted,
        expected,
        "the sandbox tier must grant EXACTLY connect + report + plugin_call, summed over \
         every capability that reaches `plugin-*`.\n\
         unexpected (possible boundary leak): {:?}\nmissing: {:?}",
        granted.difference(&expected).collect::<Vec<_>>(),
        expected.difference(&granted).collect::<Vec<_>>(),
    );
}

/// Input 7 — a `deny-*` entry is not a narrower grant, it is a global kill switch.
///
/// `RuntimeAuthority::resolve_access` reads
/// `denied_commands.get(cmd).map(|r| r.iter().any(..)).is_some()` (tauri
/// `ipc/authority.rs:446-452`): `Option::map(..).is_some()` is true whenever the KEY
/// exists, so the `any()` — the part that consults the window and the origin — is
/// computed and thrown away. One `deny-read-file` anywhere denies `read_file` to every
/// window, `main` included.
///
/// `app_commands` only collects `allow_*`, so without this test a stray `deny-` would
/// leave the tier comparisons green while the app silently lost a command — the exact
/// failure the module header claims to guard.
#[test]
fn no_capability_denies_a_command() {
    for capability in live_capabilities() {
        let denials: Vec<&String> = capability
            .permissions
            .iter()
            .filter(|p| p.starts_with("deny_") || p.contains(":deny_"))
            .collect();
        assert!(
            denials.is_empty(),
            "{} grants capability `{}` a denial: {denials:?}. Tauri treats the presence of a \
             denied command as denial for EVERY window regardless of which capability \
             declared it, so this removes the command from the host app too.",
            capability.source,
            capability.identifier,
        );
    }
}

/// Input 8 — `local` and `remote` decide the `ExecutionContext` half of the authority
/// check (`resolved.rs:218-226`), which this file otherwise ignores.
///
/// Both directions are wrong here: `"remote": {"urls": ["https://*"]}` on the host
/// capability would let any remote document loaded in `main` invoke every app command,
/// and `"local": false` would make tauri apply a capability to no local content while
/// this lockdown still counted its permissions — auditing a grant that is not in force.
#[test]
fn every_capability_is_local_and_never_remote() {
    for capability in live_capabilities() {
        assert!(
            capability.remote_urls.is_empty(),
            "{} lets capability `{}` apply to remote origins {:?}. Baram serves only local \
             content; a remote URL pattern here hands those origins this tier's commands.",
            capability.source,
            capability.identifier,
            capability.remote_urls,
        );
        assert_ne!(
            capability.local,
            Some(false),
            "{} sets `local: false` on capability `{}`, so tauri applies it to no local \
             content while this lockdown still counts its permissions as granted",
            capability.source,
            capability.identifier,
        );
    }
}

/// Kept as a diagnostic rather than as coverage: given
/// `sandbox_tier_grants_exactly_its_allowlist` and
/// `main_tier_gets_everything_except_sandbox_only_commands`, both halves below follow
/// necessarily. It fails with the clearest message of the three when a command is added to
/// `generate_handler!` and granted nowhere.
#[test]
fn every_command_granted_to_exactly_one_tier() {
    let registered = generate_handler_commands();
    let main = app_commands(&permissions_of(Tier::Host));
    let sandbox = app_commands(&permissions_of(Tier::Sandbox));

    let both: Vec<_> = main.intersection(&sandbox).collect();
    assert!(
        both.is_empty(),
        "commands granted to BOTH main and sandbox: {both:?}"
    );

    let union: BTreeSet<_> = main.union(&sandbox).cloned().collect();
    assert_eq!(
        registered,
        union,
        "every registered command must be granted to exactly one tier.\n\
         ungranted (breaks host app): {:?}\nstray grant (no such command): {:?}",
        registered.difference(&union).collect::<Vec<_>>(),
        union.difference(&registered).collect::<Vec<_>>(),
    );
}

/// §260 Phase 3c-3 — the host realm must be able to CLOSE a sandbox webview.
///
/// Found by the live smoke: `WebviewWindow.close()` was denied
/// (`core:window:allow-close` missing), so from 3c-1 onward the app could create a
/// per-plugin webview but never destroy one. Every teardown logged a swallowed
/// "Sandbox stop failed" and left the plugin RUNNING with its Rust capabilities —
/// the next load then died on the taken label. Unit tests could not see it: they
/// inject a fake window whose `close()` always resolves.
///
/// Pinned here, next to the grant it belongs to, because the symptom (a label
/// collision) points nowhere near the cause (a missing permission).
#[test]
fn host_tier_can_close_the_webviews_it_creates() {
    let host = permissions_of(Tier::Host);
    for required in [
        "core:window:allow_create",
        "core:window:allow_close",
        "core:webview:allow_create_webview_window",
    ] {
        assert!(
            host.contains(required),
            "host windows need {required}: creating a sandbox webview without being able \
             to close it leaves a running plugin that keeps its capabilities"
        );
    }
    // …and the sandbox tier must never get it — a plugin-* window holding
    // `allow-close` could close the MAIN window. `sandbox_tier_grants_exactly_its_
    // allowlist` enforces that exhaustively; this states the specific hazard.
    let window_perms: Vec<String> = permissions_of(Tier::Sandbox)
        .into_iter()
        .filter(|p| p.contains("window"))
        .collect();
    assert!(
        window_perms.is_empty(),
        "the sandbox tier must hold no window permission at all: {window_perms:?}"
    );
}

/// The logger's own IPC command must stay ungranted — to BOTH tiers.
///
/// `tauri-plugin-log` ships a `log` command (`allow-log`, default set `["allow-log"]`) that
/// lets a webview write a line of its choosing into `baram.log`. Nothing needs it: the
/// backend attaches the logger itself (`src/logging`) and no frontend code calls it.
///
/// Unlike the tier assertions, this one does not care which tier: trusted plugins run in
/// the main window's realm, so granting it there hands any installed plugin an
/// arbitrary-line writer into the file users are told to attach to bug reports — exactly
/// the deception `logging::escape_control_chars` exists to prevent.
///
/// If frontend logs are ever routed to the file (recorded in `dev/backlog.md`), this test
/// is the decision point: it must be replaced deliberately, host tier only, never
/// `plugin-*`.
#[test]
fn no_capability_grants_the_log_plugin_command() {
    for capability in live_capabilities() {
        let granted: Vec<&String> = capability
            .permissions
            .iter()
            // `log:` the PLUGIN prefix, not the substring: `allow-git-log` is one of our
            // own commands and `dialog:default` contains "log" too.
            .filter(|p| p.starts_with("log:"))
            .collect();
        assert!(
            granted.is_empty(),
            "{} grants the log plugin command to `{}`: {granted:?} — a webview could then \
             write arbitrary lines into the support log",
            capability.source,
            capability.identifier,
        );
    }
}

#[test]
fn main_tier_gets_everything_except_sandbox_only_commands() {
    let registered = generate_handler_commands();
    let main = app_commands(&permissions_of(Tier::Host));
    let mut expected = registered;
    // The sandbox-only surface: the broker plus the two transport commands whose
    // caller must be a `plugin-*` window (they'd be rejected from main anyway).
    for sandbox_only in [
        "plugin_call",
        "plugin_sandbox_connect",
        "plugin_sandbox_report",
    ] {
        expected.remove(&norm(sandbox_only));
    }
    assert_eq!(
        main,
        expected,
        "main/file-* capability must grant every command except the sandbox-only ones.\n\
         missing: {:?}\nextra: {:?}",
        expected.difference(&main).collect::<Vec<_>>(),
        main.difference(&expected).collect::<Vec<_>>(),
    );
}

/// The sandbox holds `plugin_call`, so its real authority is the broker's
/// `PluginOp` → `CapabilityRequirement` mapping, not the three permission strings this
/// file can see. A new op gated at `CapabilityRequirement::None` widens the sandbox with
/// every capability file untouched.
///
/// That mapping is guarded in `src/plugin/authorizer.rs`, and this asserts the guard is
/// still there — a deleted companion test would otherwise leave this file claiming a
/// boundary it does not cover. It checks for existence only; the mapping's correctness is
/// that test's job, not this one's.
#[test]
fn the_broker_capability_mapping_guard_still_exists() {
    let authorizer = read("src/plugin/authorizer.rs");
    for guard in [
        "fn required_capability_mapping_is_exhaustive_and_not_cross_wired",
        "fn the_adversary_attacks_every_plugin_op_variant",
    ] {
        assert!(
            authorizer.contains(guard),
            "src/plugin/authorizer.rs no longer defines `{guard}`. The sandbox tier's three \
             IPC permissions are pinned here, but what `plugin_call` will DO is pinned \
             there; without it a new PluginOp can be gated at CapabilityRequirement::None \
             and nothing fails."
        );
    }
}

// ---------------------------------------------------------------------------------------
// Permission-set expansion (2026-08-09)
//
// Everything above compares permission *identifiers*. Four of the host tier's are SETS —
// `core:default`, `dialog:default`, `opener:default`, `updater:default` — and what they
// allow is decided by tauri's and the plugins' own manifests, not by anything in this
// repository. So a dependabot bump that adds a command to `core:default` widens the host
// surface with **no diff in any file here and no test failure**. That was recorded as the
// most valuable residual when the tier model landed; this closes it by expanding the sets
// to commands and freezing the result.
//
// ‼️ This is the one part of this file that reads a BUILD ARTIFACT rather than source.
// `gen/schemas/acl-manifests.json` is where the expansion exists at all; it is gitignored
// and rewritten by `build.rs`, which cargo runs before this test compiles, so it is always
// fresh. Reading output costs this file its "the source is the truth" property, and the
// alternative — hand-copying tauri's permission sets — would be a second copy to drift.
// ---------------------------------------------------------------------------------------

/// Where tauri-build writes the resolved ACL manifests.
const ACL_MANIFESTS: &str = "gen/schemas/acl-manifests.json";
/// tauri-utils `acl/mod.rs:50` — the manifest key for the app's own commands.
const APP_ACL_KEY: &str = "__app-acl__";

/// The host tier's plugin/core command surface, frozen.
///
/// ‼️ A tauri or plugin upgrade that widens one of the four `*:default` sets makes this
/// list wrong, and that is the point: re-freeze **deliberately**, having looked at what the
/// new command does, rather than inheriting it. `the_host_tier_plugin_command_surface_is_frozen`
/// prints the diff in both directions.
///
/// The app-command half of the same expansion is NOT frozen — it is derived from
/// `generate_handler!` instead (see `the_host_tier_expands_to_the_registered_app_commands`),
/// because it changes whenever we add a command and a frozen copy would just be churn.
const HOST_PLUGIN_COMMANDS: &[&str] = &[
    "clipboard-manager:write_image",
    "clipboard-manager:write_text",
    "core:app:bundle_type",
    "core:app:identifier",
    "core:app:name",
    "core:app:register_listener",
    "core:app:remove_listener",
    "core:app:supports_multiple_windows",
    "core:app:tauri_version",
    "core:app:version",
    "core:event:emit",
    "core:event:emit_to",
    "core:event:listen",
    "core:event:unlisten",
    "core:image:from_bytes",
    "core:image:from_path",
    "core:image:new",
    "core:image:rgba",
    "core:image:size",
    "core:menu:append",
    "core:menu:create_default",
    "core:menu:get",
    "core:menu:insert",
    "core:menu:is_checked",
    "core:menu:is_enabled",
    "core:menu:items",
    "core:menu:new",
    "core:menu:popup",
    "core:menu:prepend",
    "core:menu:remove",
    "core:menu:remove_at",
    "core:menu:set_accelerator",
    "core:menu:set_as_app_menu",
    "core:menu:set_as_help_menu_for_nsapp",
    "core:menu:set_as_window_menu",
    "core:menu:set_as_windows_menu_for_nsapp",
    "core:menu:set_checked",
    "core:menu:set_enabled",
    "core:menu:set_icon",
    "core:menu:set_text",
    "core:menu:text",
    "core:path:basename",
    "core:path:dirname",
    "core:path:extname",
    "core:path:is_absolute",
    "core:path:join",
    "core:path:normalize",
    "core:path:resolve",
    "core:path:resolve_directory",
    "core:resources:close",
    "core:tray:get_by_id",
    "core:tray:new",
    "core:tray:remove_by_id",
    "core:tray:set_icon",
    "core:tray:set_icon_as_template",
    "core:tray:set_icon_with_as_template",
    "core:tray:set_menu",
    "core:tray:set_show_menu_on_left_click",
    "core:tray:set_temp_dir_path",
    "core:tray:set_title",
    "core:tray:set_tooltip",
    "core:tray:set_visible",
    "core:webview:create_webview_window",
    "core:webview:get_all_webviews",
    "core:webview:internal_toggle_devtools",
    "core:webview:webview_position",
    "core:webview:webview_size",
    "core:window:activity_name",
    "core:window:available_monitors",
    "core:window:close",
    "core:window:create",
    "core:window:current_monitor",
    "core:window:cursor_position",
    "core:window:get_all_windows",
    "core:window:inner_position",
    "core:window:inner_size",
    "core:window:internal_toggle_maximize",
    "core:window:is_always_on_top",
    "core:window:is_closable",
    "core:window:is_decorated",
    "core:window:is_enabled",
    "core:window:is_focused",
    "core:window:is_fullscreen",
    "core:window:is_maximizable",
    "core:window:is_maximized",
    "core:window:is_minimizable",
    "core:window:is_minimized",
    "core:window:is_resizable",
    "core:window:is_visible",
    "core:window:monitor_from_point",
    "core:window:outer_position",
    "core:window:outer_size",
    "core:window:primary_monitor",
    "core:window:scale_factor",
    "core:window:scene_identifier",
    "core:window:theme",
    "core:window:title",
    "dialog:message",
    "dialog:open",
    "dialog:save",
    "opener:open_url",
    "opener:reveal_item_in_dir",
    "process:restart",
    "updater:check",
    "updater:download",
    "updater:download_and_install",
    "updater:install",
];

/// Split a permission identifier into (manifest key, base name).
///
/// tauri's `Identifier` parser records the separator index on the FIRST colon, but
/// overwrites it on every subsequent colon when the identifier starts with `core:`
/// (`separator.is_none() || is_core_identifier`, tauri-utils `acl/identifier.rs:186`).
/// So `core:window:allow-close` splits at the LAST colon into (`core:window`,
/// `allow-close`), while `dialog:default` splits at the first into (`dialog`, `default`).
/// Getting this backwards would look up manifests that do not exist.
fn split_identifier(id: &str) -> (Option<&str>, &str) {
    let at = if id.starts_with("core:") {
        id.rfind(':')
    } else {
        id.find(':')
    };
    match at {
        Some(i) => (Some(&id[..i]), &id[i + 1..]),
        None => (None, id),
    }
}

#[derive(Default)]
struct Expansion {
    allow: BTreeSet<String>,
    deny: BTreeSet<String>,
    /// Permissions reached that carry a `platforms` restriction — see the assertion in
    /// `the_expansion_is_platform_independent`.
    platform_restricted: BTreeSet<String>,
}

impl Expansion {
    /// Commands with no manifest prefix: this app's own, from `generate_handler!`.
    fn app_commands(&self) -> BTreeSet<String> {
        self.allow
            .iter()
            .filter(|c| !c.contains(':'))
            .cloned()
            .collect()
    }
    /// Commands belonging to core or a plugin.
    fn plugin_commands(&self) -> BTreeSet<String> {
        self.allow
            .iter()
            .filter(|c| c.contains(':'))
            .cloned()
            .collect()
    }
}

struct Resolver {
    acl: serde_json::Value,
    seen: BTreeSet<String>,
}

impl Resolver {
    fn new() -> Self {
        let acl: serde_json::Value =
            serde_json::from_str(&read(ACL_MANIFESTS)).unwrap_or_else(|e| {
                panic!(
                    "parse {ACL_MANIFESTS}: {e}. build.rs writes it; if it is missing, the \
                     build did not run before this test"
                )
            });
        Self::from_value(acl)
    }

    /// Injectable so `the_two_resolution_orders_are_not_interchangeable` can feed a manifest
    /// where a set and a permission share a name — the real ones contain no such collision,
    /// which is what made the precedence unobservable until this existed.
    fn from_value(acl: serde_json::Value) -> Self {
        Self {
            acl,
            seen: BTreeSet::new(),
        }
    }

    fn manifest(&self, key: &str, whose: &str) -> &serde_json::Value {
        let m = &self.acl[key];
        assert!(
            !m.is_null(),
            "{whose} names manifest `{key}`, which {ACL_MANIFESTS} does not define"
        );
        m
    }

    fn collect(&mut self, key: &str, name: &str, out: &mut Expansion) {
        let permission = self.acl[key]["permissions"][name].clone();
        if permission["platforms"].is_array() {
            out.platform_restricted.insert(format!("{key}:{name}"));
        }
        for (field, bucket) in [
            ("allow", &mut out.allow as &mut BTreeSet<String>),
            ("deny", &mut out.deny),
        ] {
            for command in permission["commands"][field]
                .as_array()
                .map(|a| a.as_slice())
                .unwrap_or_default()
                .iter()
                .filter_map(|c| c.as_str())
            {
                bucket.insert(if key == APP_ACL_KEY {
                    command.to_string()
                } else {
                    format!("{key}:{command}")
                });
            }
        }
    }

    /// Mirrors `get_permissions` (tauri-utils `resolved.rs:340`) — the ENTRY point, used for
    /// a capability's declared permissions. Order here is `default`, then permission SETS,
    /// then permissions.
    fn expand_declared(&mut self, id: &str, out: &mut Expansion) {
        let (prefix, name) = split_identifier(id);
        let key = prefix.unwrap_or(APP_ACL_KEY).to_string();
        let name = name.to_string();
        self.manifest(&key, id);
        if name == "default" {
            if self.first_visit("default", &key, &name) {
                self.expand_default(&key, out);
            }
        } else if !self.acl[&key]["permission_sets"][&name].is_null() {
            if self.first_visit("set", &key, &name) {
                self.expand_set_members(&key, &name, out);
            }
        } else if !self.acl[&key]["permissions"][&name].is_null() {
            if self.first_visit("permission", &key, &name) {
                self.collect(&key, &name, out);
            }
        } else {
            panic!("{ACL_MANIFESTS} defines neither a permission nor a set named `{name}` in `{key}` (declared as `{id}`)");
        }
    }

    /// The cycle guard is keyed on the resolution KIND as well as the name.
    ///
    /// ‼️ Keying on `key:name` alone was wrong and the synthetic-manifest test caught it: a
    /// set and a permission may share a name — that collision *is* the shadowing attack —
    /// and a name-only guard made the set's visit block the permission's, dropping a command
    /// tauri would have collected. tauri has no guard here at all (a true cycle would blow
    /// its stack, loudly, at build time), so the guard must not change the outcome in any
    /// case tauri can actually resolve.
    fn first_visit(&mut self, kind: &str, key: &str, name: &str) -> bool {
        self.seen.insert(format!("{kind}\u{1}{key}\u{1}{name}"))
    }

    /// Mirrors `get_permission_set_permissions` (tauri-utils `resolved.rs:375`) — used for a
    /// member of a set. ‼️Its order is the OPPOSITE of the entry point: permissions are
    /// checked BEFORE sets. That asymmetry is not cosmetic — it is exactly why a
    /// hand-written `[[set]]` can shadow an already-granted permission id at the entry
    /// point and still resolve its own name to the real permission inside itself, instead of
    /// recursing. Reversing it here would expand the attack differently from tauri.
    fn expand_set_member(&mut self, member: &str, current_key: &str, out: &mut Expansion) {
        let (prefix, base) = split_identifier(member);
        let (key, name) = match prefix {
            // In the fallback tauri keeps the WHOLE member string as the name, not its base.
            Some(p) if !self.acl[p].is_null() => (p.to_string(), base.to_string()),
            _ => (current_key.to_string(), member.to_string()),
        };
        if name == "default" {
            if self.first_visit("default", &key, &name) {
                self.expand_default(&key, out);
            }
        } else if !self.acl[&key]["permissions"][&name].is_null() {
            if self.first_visit("permission", &key, &name) {
                self.collect(&key, &name, out);
            }
        } else if !self.acl[&key]["permission_sets"][&name].is_null() {
            if self.first_visit("set", &key, &name) {
                self.expand_set_members(&key, &name, out);
            }
        } else {
            panic!("set member `{member}` resolves to `{key}:{name}`, which {ACL_MANIFESTS} does not define");
        }
    }

    fn expand_default(&mut self, key: &str, out: &mut Expansion) {
        let members = self.members_of(&self.acl[key]["default_permission"].clone());
        for m in members {
            self.expand_set_member(&m, key, out);
        }
    }

    fn expand_set_members(&mut self, key: &str, name: &str, out: &mut Expansion) {
        let members = self.members_of(&self.acl[key]["permission_sets"][name].clone());
        for m in members {
            self.expand_set_member(&m, key, out);
        }
    }

    fn members_of(&self, set: &serde_json::Value) -> Vec<String> {
        set["permissions"]
            .as_array()
            .map(|a| a.as_slice())
            .unwrap_or_default()
            .iter()
            .filter_map(|p| p.as_str())
            .map(str::to_string)
            .collect()
    }
}

/// Expand every permission the tier declares down to the commands it actually allows.
///
/// The `seen` set is a test-only cycle guard. tauri has none — a cyclic set would blow its
/// stack — so a cycle is a loud build failure there and must not be silently absorbed here
/// either; it would simply show up as commands missing from the frozen list.
fn expanded_commands(tier: Tier) -> Expansion {
    let mut resolver = Resolver::new();
    let mut out = Expansion::default();
    let mut declared = 0usize;
    for capability in live_capabilities() {
        if tier_of(capability) != Some(tier) {
            continue;
        }
        for id in &capability.raw_permissions {
            resolver.expand_declared(id, &mut out);
            declared += 1;
        }
    }
    assert!(
        declared > 0,
        "expanded no declared permission for the {tier:?} tier — the expansion would then \
         be arguing about an empty set"
    );
    out
}

/// The sandbox must reach exactly three commands, and none of them core's or a plugin's.
///
/// This is the same property `sandbox_tier_grants_exactly_its_allowlist` asserts, one layer
/// down — and the layer matters. That test compares the three permission *identifiers*;
/// this one compares what they EXPAND to, so it independently catches a hand-written
/// `permissions/**` `[[set]]` that redefines one of those ids to also allow `read_file`
/// (`the_app_acl_manifest_has_no_handwritten_permissions` catches the same attack by
/// policing the directory — two guards, different evidence).
#[test]
fn the_sandbox_tier_expands_to_exactly_its_three_commands() {
    let expansion = expanded_commands(Tier::Sandbox);
    let expected: BTreeSet<String> = [
        "plugin_call",
        "plugin_sandbox_connect",
        "plugin_sandbox_report",
    ]
    .into_iter()
    .map(str::to_string)
    .collect();
    assert_eq!(
        expansion.app_commands(),
        expected,
        "the sandbox tier's permissions must expand to exactly the broker and its two \
         transport commands.\nunexpected: {:?}\nmissing: {:?}",
        expansion
            .app_commands()
            .difference(&expected)
            .collect::<Vec<_>>(),
        expected
            .difference(&expansion.app_commands())
            .collect::<Vec<_>>(),
    );
    assert!(
        expansion.plugin_commands().is_empty(),
        "the sandbox tier reaches core/plugin commands: {:?}. Its three permissions are \
         app-owned, so anything with a manifest prefix means a set-style permission was \
         added or an app permission now expands into one",
        expansion.plugin_commands()
    );
}

/// The host's app-command surface, derived rather than frozen.
///
/// Catches the mirror image of the sandbox case: an app permission whose `commands.allow`
/// has been redefined to include commands it does not name.
#[test]
fn the_host_tier_expands_to_the_registered_app_commands() {
    let expansion = expanded_commands(Tier::Host);
    let mut expected = generate_handler_commands();
    for sandbox_only in [
        "plugin_call",
        "plugin_sandbox_connect",
        "plugin_sandbox_report",
    ] {
        expected.remove(&norm(sandbox_only));
    }
    let got: BTreeSet<String> = expansion.app_commands().iter().map(|c| norm(c)).collect();
    assert_eq!(
        got,
        expected,
        "the host tier's app permissions must expand to exactly the registered commands \
         minus the sandbox-only ones.\nunexpected (a permission expanded wider than its \
         name): {:?}\nmissing: {:?}",
        got.difference(&expected).collect::<Vec<_>>(),
        expected.difference(&got).collect::<Vec<_>>(),
    );
}

#[test]
fn the_host_tier_plugin_command_surface_is_frozen() {
    let expansion = expanded_commands(Tier::Host);
    let got = expansion.plugin_commands();
    let expected: BTreeSet<String> = HOST_PLUGIN_COMMANDS.iter().map(|s| s.to_string()).collect();
    assert_eq!(
        expected.len(),
        HOST_PLUGIN_COMMANDS.len(),
        "HOST_PLUGIN_COMMANDS contains a duplicate, so its length overstates what it pins"
    );
    assert_eq!(
        got,
        expected,
        "the host tier's core/plugin command surface changed.\n\
         GAINED (a dependency upgrade widened a `*:default` set, or a permission was added \
         — look at what each of these does before re-freezing): {:?}\n\
         LOST (a set narrowed, or a permission was removed): {:?}",
        got.difference(&expected).collect::<Vec<_>>(),
        expected.difference(&got).collect::<Vec<_>>(),
    );
}

/// A denial reaching either tier through an expansion is a global kill switch, for the
/// reason `no_capability_denies_a_command` explains — and that test only sees denials
/// written directly in a capability file, not one arriving inside a `*:default` set.
#[test]
fn no_expansion_reaches_a_denied_command() {
    for tier in [Tier::Host, Tier::Sandbox] {
        let expansion = expanded_commands(tier);
        assert!(
            expansion.deny.is_empty(),
            "the {tier:?} tier expands to denied commands {:?}. Tauri denies a command for \
             EVERY window once any capability denies it, so this removes the command from \
             the host app as well",
            expansion.deny
        );
    }
}

/// The two resolution orders are opposite, and that is load-bearing — pinned against a
/// synthetic manifest because the real ones have no name collision to expose it.
///
/// tauri checks permission SETS before permissions at the entry point
/// (`get_permissions`, `resolved.rs:358` vs `:360`) and permissions before SETS inside a set
/// (`get_permission_set_permissions`, `:407` vs `:413`). That asymmetry is exactly why a
/// hand-written `[[set]]` named after an already-granted permission can shadow it at the
/// entry point *and* still resolve its own name to the real permission inside itself,
/// instead of recursing — i.e. why the attack is silent rather than a build hang.
///
/// A fixture where `shared` is BOTH a set and a permission separates all three orders:
///   - faithful:                    {from_permission, from_other}
///   - permission-first at entry:    {from_permission}
///   - set-first inside a set:                        {from_other}  (cycle guard absorbs it)
///
/// Without this, swapping either order left all 21 tests green.
#[test]
fn the_two_resolution_orders_are_not_interchangeable() {
    let acl = serde_json::json!({
        APP_ACL_KEY: {
            "permissions": {
                "shared": { "identifier": "shared", "commands": { "allow": ["from_permission"] } },
                "other":  { "identifier": "other",  "commands": { "allow": ["from_other"] } }
            },
            "permission_sets": {
                "shared": { "identifier": "shared", "permissions": ["shared", "other"] }
            }
        }
    });
    let mut resolver = Resolver::from_value(acl);
    let mut out = Expansion::default();
    resolver.expand_declared("shared", &mut out);
    let expected: BTreeSet<String> = ["from_other", "from_permission"]
        .into_iter()
        .map(str::to_string)
        .collect();
    assert_eq!(
        out.allow, expected,
        "`shared` is both a set and a permission. Getting {:?} instead of {expected:?} means a \
         resolution order no longer matches tauri: only {{from_permission}} means the entry \
         point stopped preferring the SET, and only {{from_other}} means a set member stopped \
         preferring the PERMISSION.",
        out.allow,
    );
}

/// The frozen list is platform-independent only while nothing it reaches is
/// platform-restricted; tauri filters those by target at resolve time
/// (`Permission::is_active`), so one would make the real surface differ between a macOS
/// developer and Linux CI while this expansion kept reporting the union.
#[test]
fn the_expansion_is_platform_independent() {
    for tier in [Tier::Host, Tier::Sandbox] {
        let expansion = expanded_commands(tier);
        assert!(
            expansion.platform_restricted.is_empty(),
            "the {tier:?} tier reaches platform-restricted permissions {:?}. Decide whether \
             the frozen list should be the union or per-target before re-freezing — silently \
             taking the union makes this test stricter on some platforms than the ACL is",
            expansion.platform_restricted
        );
    }
}
