// §55 Pandoc Extended Export — Pandoc 감지, 실행, 커스텀 Export

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::path::Path;
use std::process::Command;
use tempfile::tempdir;

use super::pandoc_images::{stage_images, ImageStaging};
use super::ExportError;

/// Pandoc installation information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PandocInfo {
    pub path: String,
    pub version: String,
    pub available: bool,
}

/// Options for Pandoc export
#[allow(dead_code)]
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PandocExportOptions {
    /// Target format: "docx", "latex", "epub", "rst"
    pub format: String,
    /// Word reference document (template) path
    pub reference_doc: Option<String>,
    /// Additional Pandoc CLI arguments
    pub extra_args: Vec<String>,
}

/// A binary asset (e.g. rasterized Mermaid PNG) written alongside the Pandoc
/// input so Pandoc can embed it. `data` arrives as a JSON number array.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PandocAsset {
    pub name: String,
    pub data: Vec<u8>,
}

/// Replace `baram-asset:NAME` placeholders with each asset's absolute path,
/// written as an angle-bracket destination (`<C:\\Users\\Jane Doe\\…>`): a
/// temporary directory under a user name with a space is not one token to
/// the markdown parser otherwise, and every image would silently become its
/// alt text. Temp paths contain neither `<`, `>` nor a newline, the three
/// characters such a destination cannot hold.
///
/// Replacement is performed longest-name-first so one asset name being a
/// prefix of another (e.g. "img" vs "img2") cannot clobber the longer
/// placeholder; this also makes the result independent of HashMap order.
fn rewrite_asset_refs(markdown: &str, name_to_path: &HashMap<String, String>) -> String {
    let mut entries: Vec<(&String, &String)> = name_to_path.iter().collect();
    entries.sort_by_key(|(name, _)| std::cmp::Reverse(name.len()));
    let mut result = markdown.to_string();
    for (name, path) in entries {
        result = result.replace(&format!("baram-asset:{}", name), &format!("<{path}>"));
    }
    result
}

/// A safe asset name is a single file name — exactly one normal path
/// component, so joining it under the temp dir cannot escape that dir. Judged
/// with the platform's own path rules rather than by scanning for separators:
/// on Windows `C:evil.dll` has no separator, yet `PathBuf::push` treats a
/// drive prefix as a fresh path and `tmp_dir.join(..)` would write into the
/// current directory of drive C.
pub(super) fn is_safe_asset_name(name: &str) -> bool {
    use std::path::Component;
    // Both separators are refused on every platform: a name is generated by
    // the frontend and never legitimately holds either, whatever the host.
    // Nor a control character or an angle bracket: the name ends up inside
    // the `<…>` destination `rewrite_asset_refs` writes, which neither a
    // newline nor a `>` may cut short. Nor what Windows would quietly turn
    // into another file — a trailing dot or space is dropped there, so two
    // names could land on one file — or into a device (`CON`, `NUL`, …),
    // which `File::create` would open. Nor the names of the markdown input
    // and the policy filter, which share the directory.
    if name
        .chars()
        .any(|c| c == '/' || c == '\\' || c == '<' || c == '>' || c.is_control())
        || name.ends_with('.')
        || name.ends_with(' ')
        || name.eq_ignore_ascii_case(INPUT_FILE_NAME)
        || name.eq_ignore_ascii_case(POLICY_FILTER_NAME)
    {
        return false;
    }
    let stem = name.split('.').next().unwrap_or(name).to_ascii_uppercase();
    if WINDOWS_DEVICE_NAMES.contains(&stem.as_str()) {
        return false;
    }
    let mut components = Path::new(name).components();
    matches!(
        (components.next(), components.next()),
        (Some(Component::Normal(only)), None) if only == name
    )
}

/// The markdown pandoc reads, written into the same temporary directory as
/// the assets — so no asset may take its name.
const INPUT_FILE_NAME: &str = "baram-pandoc-input.md";

/// The Lua filter pandoc runs over the parsed document (issue 545), written
/// next to the input; no asset may take its name either.
const POLICY_FILTER_NAME: &str = "baram-export-policy.lua";

/// issue 545: what pandoc may read is decided by the app, never by the
/// document. The markdown image pass on the frontend sees markdown images
/// only; this filter runs on pandoc's OWN parse of the document, so its
/// reader and not a second parser decides what is an image, what is raw
/// HTML and what is metadata:
///
/// - Every `Image` whose source is not one of the paths this export bound
///   (`ALLOWED`, generated per export) becomes its alt text. That closes what
///   no string pass can see — markdown pandoc re-parses inside an HTML block
///   (`<div>` … `![](/outside)` … `</div>`, one `html` node to remark) — and
///   any other way a path could reach the markdown string.
/// - Every `Link` whose target has a scheme outside the app's link policy
///   (`isAllowedLinkHref`, src/utils/link-href.ts) becomes its label, for the
///   same reason: the frontend's link pass sees markdown links only.
/// - Raw HTML is dropped, except that `<br>` becomes a line break. The epub
///   writer turns `<img src>`, `<video>`, `<object>` and the rest into
///   embedded files (verified on pandoc 3.11 — `<img src="/etc/passwd">`
///   landed in `EPUB/media/`) and fetches an `https:` one. The docx, latex
///   and rst writers ignored raw HTML already, so only EPUB output changes:
///   raw HTML written into a note no longer passes through to it. `<br>` is
///   what the editor writes for a line break inside a table cell, so it is
///   kept as the break it means — in docx too, which dropped it before.
/// - Metadata keys that name a file are dropped. A note's YAML frontmatter is
///   pandoc metadata, and `cover-image` and `css` make the epub writer read
///   those paths.
const POLICY_FILTER_BODY: &str = r#"
local LINK_SCHEMES = {
  http = true, https = true, ftp = true, ftps = true, mailto = true,
  tel = true, callto = true, sms = true, cid = true, xmpp = true, matrix = true,
}
local function link_allowed(target)
  if target == nil or target == "" then return true end
  if target:match("^[/\\][/\\]") then return false end
  local scheme = target:match("^([%a][%w+.-]*):")
  if scheme == nil then return true end
  return LINK_SCHEMES[scheme:lower()] == true
end
local function drop_html(el)
  if el.format == "html" or el.format == "html5" or el.format == "html4" then
    if el.text:match("^<[Bb][Rr]%s*/?>$") then return pandoc.LineBreak() end
    return {}
  end
end
local FILE_KEYS = { "cover-image", "epub-cover-image", "css", "stylesheet", "bibliography", "csl" }
return {
  {
    Image = function(el)
      if not ALLOWED[el.src] then return el.caption end
    end,
    Link = function(el)
      if not link_allowed(el.target) then return el.content end
    end,
    RawInline = drop_html,
    RawBlock = drop_html,
    Meta = function(meta)
      for _, key in ipairs(FILE_KEYS) do
        meta[key] = nil
      end
      return meta
    end,
  },
}
"#;

/// The policy filter for one export: the paths its images may have, then the
/// body above. A path is written as a Lua string with only `\` and `"`
/// escaped — asset names admit no control character or quote-like trouble
/// (`is_safe_asset_name`), and the temporary directory comes from the OS.
fn policy_filter(allowed_paths: &[&str]) -> String {
    let mut lua = String::from(
        "-- issue 545 (Baram): pandoc reads only what the app staged for it.\nlocal ALLOWED = {\n",
    );
    for path in allowed_paths {
        let escaped = path.replace('\\', "\\\\").replace('"', "\\\"");
        lua.push_str(&format!("  [\"{escaped}\"] = true,\n"));
    }
    lua.push_str("}\n");
    lua.push_str(POLICY_FILTER_BODY);
    lua
}

/// A bound path as it is written into the markdown destination and the
/// filter's allowlist: forward slashes on Windows. A backslash before
/// punctuation is an escape in a markdown destination (`Temp\.tmpAbc` would
/// read as `Temp.tmpAbc`), and Windows opens either separator.
fn markdown_path(path: &Path) -> String {
    let text = path.to_string_lossy();
    if cfg!(windows) {
        text.replace('\\', "/")
    } else {
        text.into_owned()
    }
}

/// Names Windows reserves for devices, with any extension (`CON.png` too).
const WINDOWS_DEVICE_NAMES: &[&str] = &[
    "CON", "PRN", "AUX", "NUL", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8",
    "COM9", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9",
];

/// Custom export command definition
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomExportItem {
    pub name: String,
    /// Shell command with variable placeholders: ${file}, ${basename}, ${output_dir}, ${vault_dir}
    pub command: String,
    pub extension: String,
    pub show_in_menu: bool,
}

/// The writers the export offers, each with the output suffix it must be
/// written to. `docx` and `epub` embed images (pandoc reads the files);
/// `latex` and `rst` write the reference and open nothing — which is why the
/// frontend's image policy is keyed to the same set. pandoc decides to
/// PRODUCE A PDF from a `.pdf` output name even with `--to latex` (latex then
/// names the intermediate), and a TeX engine reads every `\includegraphics`
/// path — so a "latex" export, whose images pass through unchecked, must not
/// be allowed to land in a `.pdf`.
fn required_extension(format: &str) -> Option<&'static str> {
    match format {
        "docx" => Some("docx"),
        "epub" => Some("epub"),
        "latex" => Some("tex"),
        "rst" => Some("rst"),
        _ => None,
    }
}

/// Allowlist of permitted Pandoc CLI flags for extra_args validation.
///
/// `--from` is deliberately absent. The reader is fixed to `markdown` when the
/// command is built and extra args are appended AFTER it, so an allowed
/// `--from` would silently replace that profile — and the frontend's export
/// link policy (issue 527) relies on it: `+autolink_bare_uris` alone would turn
/// the plain text that policy leaves behind back into live links.
///
/// `--pdf-engine` is absent too: no format offered here produces a PDF, and
/// the suffix check in `run_pandoc` is what keeps pandoc from starting one.
///
/// `--to` is absent for the same reason on the other side (issue 545): the
/// writer is bound to `format` when the command is built, and the frontend's
/// image policy runs only for the formats that embed images. A `--to` that
/// picked another writer — or an output suffix pandoc would otherwise infer
/// the writer from — could turn a "latex" export, whose images pass through
/// unchecked, into a docx that embeds them.
///
/// `--metadata` and `--variable` are absent as well (issue 545): a key is a
/// file to some writers — `--metadata cover-image=<path>` makes the epub
/// writer embed that file, `--variable css=<path>` makes it read that one as
/// a stylesheet — and the validator judges the flag, not the key. Nothing in
/// the app sends either; the list is what a forged request may still say.
const ALLOWED_PANDOC_FLAGS: &[&str] = &[
    "--standalone",
    "--toc",
    "--toc-depth",
    "--columns",
    "--wrap",
    "--number-sections",
    "--table-of-contents",
    "--highlight-style",
    "--slide-level",
    "--shift-heading-level-by",
];

/// Reject any caller-supplied pandoc argument outside `ALLOWED_PANDOC_FLAGS`.
/// `--flag=value` and `--flag value` forms are judged by their flag name.
fn validate_extra_args(extra_args: &[String]) -> Result<(), ExportError> {
    for arg in extra_args {
        let flag = arg.split('=').next().unwrap_or(arg);
        let flag_base = flag.split(' ').next().unwrap_or(flag);
        if !ALLOWED_PANDOC_FLAGS.contains(&flag_base) {
            return Err(ExportError::PandocFailed(format!(
                "Disallowed pandoc argument: {}",
                flag_base
            )));
        }
    }
    Ok(())
}

/// Common Pandoc installation paths to probe when bare "pandoc" fails.
/// Covers Homebrew (Apple Silicon + Intel), system paths, and common installers.
const PANDOC_SEARCH_PATHS: &[&str] = &[
    "/opt/homebrew/bin/pandoc",
    "/usr/local/bin/pandoc",
    "/usr/bin/pandoc",
    "/opt/local/bin/pandoc",
];

/// Try running `pandoc --version` at the given path.
fn try_pandoc(path: &str) -> Option<PandocInfo> {
    let output = Command::new(path).arg("--version").output().ok()?;
    if output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        Some(PandocInfo {
            path: path.to_string(),
            version: parse_pandoc_version(&stdout),
            available: true,
        })
    } else {
        None
    }
}

/// Detect Pandoc installation by running `pandoc --version`.
/// When a bare name like "pandoc" fails (common in sandboxed .app bundles
/// where PATH is limited to /usr/bin:/bin), probes well-known install paths.
pub fn detect_pandoc(pandoc_path: &str) -> PandocInfo {
    // 1. Try the user-supplied (or default) path first
    if let Some(info) = try_pandoc(pandoc_path) {
        return info;
    }

    // 2. If the caller passed an absolute path that failed, don't probe further
    if pandoc_path.starts_with('/') {
        return PandocInfo {
            path: pandoc_path.to_string(),
            version: String::new(),
            available: false,
        };
    }

    // 3. Probe well-known paths (handles .app bundle limited PATH)
    for candidate in PANDOC_SEARCH_PATHS {
        if let Some(info) = try_pandoc(candidate) {
            return info;
        }
    }

    PandocInfo {
        path: pandoc_path.to_string(),
        version: String::new(),
        available: false,
    }
}

/// Parse version string from `pandoc --version` output.
/// First line is typically: `pandoc X.Y.Z` or `pandoc X.Y.Z.W`
fn parse_pandoc_version(output: &str) -> String {
    output
        .lines()
        .next()
        .and_then(|line| {
            // "pandoc 3.1.9" -> "3.1.9"
            line.strip_prefix("pandoc ")
                .or_else(|| line.strip_prefix("pandoc.exe "))
        })
        .unwrap_or("unknown")
        .trim()
        .to_string()
}

/// Run Pandoc to convert a markdown file to the specified format.
///
/// 1. Writes markdown content to a temp file
/// 2. Runs pandoc with the specified options
/// 3. Output is written to `output_path`
///
/// `images` (issue 545): the document's own relative images, staged into the
/// same temporary directory behind the vault boundary — see `pandoc_images.rs`.
/// `None` when the format embeds nothing or the document names no image.
pub fn run_pandoc(
    markdown_content: &str,
    output_path: &str,
    pandoc_path: &str,
    options: &PandocExportOptions,
    assets: &[PandocAsset],
    images: Option<&ImageStaging<'_>>,
) -> Result<(), ExportError> {
    // 0. The writer is decided HERE, from `format`, never inferred from the
    // output's suffix or picked by an extra argument (issue 545) — and the
    // suffix must agree with it, or pandoc would turn a `.pdf` into a PDF run.
    let Some(required) = required_extension(&options.format) else {
        return Err(ExportError::PandocFailed(format!(
            "Unsupported export format: {}",
            options.format
        )));
    };
    let extension = Path::new(output_path)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_ascii_lowercase());
    if extension.as_deref() != Some(required) {
        return Err(ExportError::PandocFailed(format!(
            "A {} export must be written to a .{required} file",
            options.format
        )));
    }

    // 1. Write markdown (with assets) to temp dir
    let tmp_dir = tempdir().map_err(|e| ExportError::TempFileError(e.to_string()))?;

    // 1a. Write each asset next to the input and map name -> absolute path.
    // Names are taken case-insensitively: on a case-insensitive volume two
    // spellings are one file, and the second write would replace the first.
    let mut name_to_path: HashMap<String, String> = HashMap::new();
    let mut taken: HashSet<String> = HashSet::new();
    let mut take = |name: &str| -> Result<(), ExportError> {
        if taken.insert(name.to_ascii_lowercase()) {
            Ok(())
        } else {
            Err(ExportError::TempFileError(format!(
                "Duplicate asset name: {name}"
            )))
        }
    };
    for asset in assets {
        if !is_safe_asset_name(&asset.name) {
            return Err(ExportError::TempFileError(format!(
                "Unsafe asset name: {}",
                asset.name
            )));
        }
        take(&asset.name)?;
        let asset_path = tmp_dir.path().join(&asset.name);
        std::fs::write(&asset_path, &asset.data)
            .map_err(|e| ExportError::TempFileError(e.to_string()))?;
        name_to_path.insert(asset.name.clone(), markdown_path(&asset_path));
    }

    // 1b. issue 545: the document's own images, staged into the same directory
    // behind the vault boundary (`pandoc_images.rs`); a broken link is bound
    // to a path that does not exist, so pandoc never resolves a bare name.
    if let Some(staging) = images {
        // A request wearing a diagram's name would overwrite that diagram's
        // file; the export is not shipped with the swap.
        for req in staging.requests {
            take(&req.name)?;
        }
        for (name, path) in stage_images(tmp_dir.path(), staging)? {
            name_to_path.insert(name, markdown_path(Path::new(&path)));
        }
    }

    // 1c. Rewrite baram-asset: references to absolute paths
    let markdown_content = rewrite_asset_refs(markdown_content, &name_to_path);

    let input_path = tmp_dir.path().join(INPUT_FILE_NAME);
    std::fs::write(&input_path, &markdown_content)
        .map_err(|e| ExportError::TempFileError(e.to_string()))?;
    // 1d. issue 545: the policy filter, pandoc's side of the boundary — with
    // the paths this export bound as the only sources an image may have.
    let filter_path = tmp_dir.path().join(POLICY_FILTER_NAME);
    let allowed: Vec<&str> = name_to_path.values().map(String::as_str).collect();
    std::fs::write(&filter_path, policy_filter(&allowed))
        .map_err(|e| ExportError::TempFileError(e.to_string()))?;

    // 2. Build pandoc command
    let mut cmd = Command::new(pandoc_path);
    cmd.arg(input_path.to_str().unwrap_or("input.md"))
        .arg("-o")
        .arg(output_path)
        .arg("--from")
        .arg("markdown")
        .arg("--to")
        .arg(&options.format)
        .arg("--lua-filter")
        .arg(&filter_path);

    // Add reference doc for docx
    if let Some(ref ref_doc) = options.reference_doc {
        if !ref_doc.is_empty() {
            cmd.arg("--reference-doc").arg(ref_doc);
        }
    }

    // Add extra args — validated against the allowlist first
    validate_extra_args(&options.extra_args)?;
    for arg in &options.extra_args {
        cmd.arg(arg);
    }

    // 3. Execute
    let output = cmd
        .output()
        .map_err(|e| ExportError::PandocNotFound(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(ExportError::PandocFailed(stderr.to_string()));
    }

    Ok(())
}

/// Characters disallowed in variable values to prevent shell injection.
const DANGEROUS_CHARS: &[char] = &[';', '&', '|', '`', '$', '(', ')', '\n', '\r'];

/// Expand `${key}` placeholders in `template` with values from `vars`.
/// Returns an error if any variable value contains shell metacharacters.
fn expand_variables(template: &str, vars: &HashMap<String, String>) -> Result<String, ExportError> {
    let mut result = template.to_string();
    for (key, value) in vars {
        if value.chars().any(|c| DANGEROUS_CHARS.contains(&c)) {
            return Err(ExportError::CustomExportFailed(format!(
                "Variable '{}' contains disallowed characters",
                key
            )));
        }
        result = result.replace(&format!("${{{}}}", key), value);
    }
    Ok(result)
}

/// Run a custom export command with variable substitution.
///
/// Security: uses `shlex` to parse the expanded command into argv tokens and
/// executes directly via `Command::new` — no shell (`sh -c` / `cmd /C`) is
/// involved, preventing command injection.
///
/// Supported variables:
/// - `${file}` — full path of the source file
/// - `${basename}` — file name without extension
/// - `${output_dir}` — directory of the output path
/// - `${vault_dir}` — workspace root directory
pub fn run_custom_export(command: &str, vars: &HashMap<String, String>) -> Result<(), ExportError> {
    let expanded = expand_variables(command, vars)?;

    let parts = shlex::split(&expanded).ok_or_else(|| {
        ExportError::CustomExportFailed("Invalid command syntax (mismatched quotes)".into())
    })?;
    if parts.is_empty() {
        return Err(ExportError::CustomExportFailed(
            "Empty command after expansion".into(),
        ));
    }

    let output = Command::new(&parts[0])
        .args(&parts[1..])
        .output()
        .map_err(|e| {
            ExportError::CustomExportFailed(format!("Failed to execute command: {}", e))
        })?;

    if output.status.success() {
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Err(ExportError::CustomExportFailed(format!(
            "Command failed (exit {}): {}",
            output.status.code().unwrap_or(-1),
            stderr
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::super::pandoc_images::PandocImageRequest;
    use super::*;

    #[test]
    fn test_parse_pandoc_version() {
        assert_eq!(
            parse_pandoc_version("pandoc 3.1.9\nCompiled with pandoc-types"),
            "3.1.9"
        );
        assert_eq!(parse_pandoc_version("pandoc 2.19.2"), "2.19.2");
        assert_eq!(parse_pandoc_version(""), "unknown");
    }

    #[test]
    fn extra_args_cannot_override_the_reader_profile() {
        // Issue 527: the frontend's link policy assumes `--from markdown`
        // (no autolink_bare_uris, no raw_html additions). Every spelling of a
        // reader override is refused, `-f` included (it was never listed).
        for arg in [
            "--from",
            "--from=markdown+autolink_bare_uris",
            "--from markdown+raw_html",
            "-f",
        ] {
            assert!(
                validate_extra_args(&[arg.to_string()]).is_err(),
                "{arg} must be rejected"
            );
        }
    }

    #[test]
    fn extra_args_accept_allowlisted_flags_in_both_spellings() {
        let args: Vec<String> = ["--toc", "--toc-depth=2", "--wrap none"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        assert!(validate_extra_args(&args).is_ok());
        assert!(validate_extra_args(&[]).is_ok());
    }

    #[test]
    fn test_detect_pandoc_nonexistent() {
        let info = detect_pandoc("/nonexistent/pandoc");
        assert!(!info.available);
        assert_eq!(info.path, "/nonexistent/pandoc");
    }

    #[test]
    fn test_pandoc_export_options_deserialize() {
        let json = r#"{
            "format": "docx",
            "referenceDoc": "/path/to/template.docx",
            "extraArgs": ["--standalone", "--toc"]
        }"#;
        let opts: PandocExportOptions = serde_json::from_str(json).unwrap();
        assert_eq!(opts.format, "docx");
        assert_eq!(
            opts.reference_doc.as_deref(),
            Some("/path/to/template.docx")
        );
        assert_eq!(opts.extra_args, vec!["--standalone", "--toc"]);
    }

    #[test]
    fn test_pandoc_export_options_minimal() {
        let json = r#"{
            "format": "latex",
            "extraArgs": []
        }"#;
        let opts: PandocExportOptions = serde_json::from_str(json).unwrap();
        assert_eq!(opts.format, "latex");
        assert!(opts.reference_doc.is_none());
        assert!(opts.extra_args.is_empty());
    }

    #[test]
    fn test_custom_export_item_roundtrip() {
        let item = CustomExportItem {
            name: "AsciiDoc".to_string(),
            command: "pandoc ${file} -o ${basename}.adoc".to_string(),
            extension: "adoc".to_string(),
            show_in_menu: true,
        };
        let json = serde_json::to_string(&item).unwrap();
        let parsed: CustomExportItem = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.name, "AsciiDoc");
        assert_eq!(parsed.extension, "adoc");
        assert!(parsed.show_in_menu);
    }

    #[test]
    fn test_variable_substitution() {
        let mut vars = HashMap::new();
        vars.insert("file".to_string(), "/home/user/doc.md".to_string());
        vars.insert("basename".to_string(), "doc".to_string());
        vars.insert("output_dir".to_string(), "/home/user/output".to_string());

        let cmd = "pandoc ${file} -o ${output_dir}/${basename}.docx";
        let mut expanded = cmd.to_string();
        for (key, value) in &vars {
            expanded = expanded.replace(&format!("${{{}}}", key), value);
        }
        assert_eq!(
            expanded,
            "pandoc /home/user/doc.md -o /home/user/output/doc.docx"
        );
    }

    #[test]
    fn test_expand_variables_rejects_shell_metacharacters() {
        let mut vars = HashMap::new();
        vars.insert("file".to_string(), "test`rm -rf /`.md".to_string());
        let result = expand_variables("echo ${file}", &vars);
        assert!(
            result.is_err(),
            "backtick in variable value must be rejected"
        );

        let mut vars2 = HashMap::new();
        vars2.insert("file".to_string(), "foo;rm -rf /".to_string());
        let result2 = expand_variables("echo ${file}", &vars2);
        assert!(
            result2.is_err(),
            "semicolon in variable value must be rejected"
        );

        let mut vars3 = HashMap::new();
        vars3.insert("file".to_string(), "foo|cat /etc/passwd".to_string());
        let result3 = expand_variables("echo ${file}", &vars3);
        assert!(result3.is_err(), "pipe in variable value must be rejected");

        let mut vars4 = HashMap::new();
        vars4.insert("file".to_string(), "$(whoami).md".to_string());
        let result4 = expand_variables("echo ${file}", &vars4);
        assert!(
            result4.is_err(),
            "dollar sign in variable value must be rejected"
        );
    }

    #[test]
    fn test_expand_variables_allows_safe_paths() {
        let mut vars = HashMap::new();
        vars.insert("file".to_string(), "/home/user/my doc.md".to_string());
        vars.insert("basename".to_string(), "my doc".to_string());
        let result = expand_variables("pandoc ${file} -o ${basename}.docx", &vars);
        assert!(result.is_ok());
        assert_eq!(
            result.unwrap(),
            "pandoc /home/user/my doc.md -o my doc.docx"
        );
    }

    #[test]
    fn test_run_custom_export_rejects_mismatched_quotes() {
        let vars = HashMap::new();
        let result = run_custom_export("echo \"unclosed", &vars);
        assert!(result.is_err());
        let err_msg = format!("{:?}", result.unwrap_err());
        assert!(err_msg.contains("mismatched quotes"));
    }

    #[test]
    fn test_pandoc_info_serialize() {
        let info = PandocInfo {
            path: "/usr/bin/pandoc".to_string(),
            version: "3.1.9".to_string(),
            available: true,
        };
        let json = serde_json::to_string(&info).unwrap();
        assert!(json.contains("\"available\":true"));
        assert!(json.contains("\"version\":\"3.1.9\""));
    }

    #[test]
    fn the_writer_cannot_be_picked_by_an_extra_argument() {
        // issue 545: the image policy is keyed to `format`; a `--to` that chose
        // another writer would embed images that policy left unchecked.
        assert!(validate_extra_args(&["--to=docx".to_string()]).is_err());
        assert!(validate_extra_args(&["--to docx".to_string()]).is_err());
        assert!(validate_extra_args(&["--toc".to_string()]).is_ok());
        // A metadata key or a variable is a FILE to the epub writer.
        assert!(validate_extra_args(&["--metadata=cover-image=/etc/hosts".to_string()]).is_err());
        assert!(validate_extra_args(&["--variable css=/etc/hosts".to_string()]).is_err());
        assert!(validate_extra_args(&["--variable".to_string()]).is_err());
    }

    #[test]
    fn run_pandoc_refuses_a_format_it_does_not_offer_before_touching_anything() {
        let options = PandocExportOptions {
            format: "odt".into(),
            reference_doc: None,
            extra_args: Vec::new(),
        };
        // No pandoc binary is needed: the format is judged first.
        let err = run_pandoc(
            "x",
            "/nonexistent/out.odt",
            "/nonexistent/pandoc",
            &options,
            &[],
            None,
        )
        .expect_err("must be refused");
        assert!(matches!(err, ExportError::PandocFailed(_)), "{err}");
    }

    #[test]
    fn run_pandoc_binds_the_output_suffix_to_the_format() {
        let latex = PandocExportOptions {
            format: "latex".into(),
            reference_doc: None,
            extra_args: Vec::new(),
        };
        // `.pdf` would make pandoc run a TeX engine over the unchecked images.
        let err = run_pandoc(
            "x",
            "/nonexistent/out.pdf",
            "/nonexistent/pandoc",
            &latex,
            &[],
            None,
        )
        .expect_err("must be refused");
        assert!(
            matches!(err, ExportError::PandocFailed(ref m) if m.contains(".tex")),
            "{err}"
        );
        // The right suffix gets past the check — and fails only because there
        // is no pandoc to run.
        let err = run_pandoc(
            "x",
            "/nonexistent/out.TEX",
            "/nonexistent/pandoc",
            &latex,
            &[],
            None,
        )
        .expect_err("no pandoc here");
        assert!(matches!(err, ExportError::PandocNotFound(_)), "{err}");
        // And no extra argument may start a PDF run either.
        assert!(validate_extra_args(&["--pdf-engine=xelatex".to_string()]).is_err());
    }

    /// issue 545 — the whole path with a REAL pandoc: a vault-relative image
    /// staged through `stage_images` and a rasterized-diagram asset both land
    /// inside the docx and the epub, and nothing else does; a request for a
    /// file that is not there becomes its alt text. Ignored by default because
    /// it needs pandoc on PATH — `cargo test pandoc_smoke -- --ignored` — and it
    /// fails, rather than passes, when pandoc is missing.
    #[test]
    #[ignore]
    fn pandoc_smoke_embeds_staged_images_in_docx_and_epub() {
        // A missing pandoc is a failed prerequisite, not a pass: an ignored
        // test that returned green without running would prove nothing.
        if std::process::Command::new("pandoc")
            .arg("--version")
            .output()
            .is_err()
        {
            panic!("this smoke test needs pandoc on PATH (brew install pandoc)");
        }
        // A 1x1 PNG.
        const PNG: &[u8] = &[
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48,
            0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00,
            0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x44, 0x41, 0x54, 0x78,
            0x9C, 0x63, 0xF8, 0xCF, 0xC0, 0x00, 0x00, 0x03, 0x01, 0x01, 0x00, 0x18, 0xDD, 0x8D,
            0xB0, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
        ];
        let vault = tempfile::tempdir().unwrap();
        let root = std::fs::canonicalize(vault.path()).unwrap();
        std::fs::create_dir_all(root.join("notes/img")).unwrap();
        std::fs::write(root.join("notes/img/pic.png"), PNG).unwrap();
        let out = tempfile::tempdir().unwrap();
        // A file outside the vault that the document names every way it can
        // without a markdown image: raw HTML inline and as a block, and the
        // frontmatter keys the epub writer reads files from. None of it may
        // reach the output — the Lua policy filter drops raw HTML and those
        // keys on pandoc's own parse.
        let outside = tempfile::tempdir().unwrap();
        let canary = outside.path().join("secret.txt");
        std::fs::write(&canary, b"CANARY-BYTES-9c1f").unwrap();
        let canary = canary.to_str().unwrap();

        // What the frontend hands over: the relative image already rewritten
        // to an asset request, a diagram asset, and a refused image reduced to
        // its alt text.
        // …plus a request for a file that is not there: pandoc must replace it
        // with its alt text ("gone") and the export must still succeed.
        // …and, with the same canary, what pandoc alone can see: markdown it
        // re-parses inside an HTML block, a link the frontend's policy would
        // have refused, and a `<br>` the editor writes for a cell break.
        let pic_abs = root.join("notes/img/pic.png");
        let pic_abs = pic_abs.to_str().unwrap();
        let markdown = format!(
            "---\ntitle: T\ncover-image: {canary}\ncss: {canary}\n---\n\n# T\n\n![pic](baram-asset:image-0.png) ![d](baram-asset:mermaid-0.png) ![gone](baram-asset:image-1.png) ![abs](baram-asset:image-2.png){{width=120px}} hosts <img src=\"{canary}\" alt=\"raw\">\n\n<img src=\"{canary}\">\n\n<video src=\"{canary}\"></video>\n\n<div>\n\n![indiv](<{canary}>)\n\n</div>\n\n[bad](javascript:alert(1)) [ok](https://example.com/) one<br>two\n"
        );
        let markdown = markdown.as_str();
        let requests = vec![
            PandocImageRequest {
                name: "image-0.png".into(),
                source: "img/pic.png".into(),
            },
            PandocImageRequest {
                name: "image-1.png".into(),
                source: "img/nope.png".into(),
            },
            // An absolute path that stays inside the vault is embedded too.
            PandocImageRequest {
                name: "image-2.png".into(),
                source: pic_abs.into(),
            },
        ];
        let assets = vec![PandocAsset {
            name: "mermaid-0.png".into(),
            data: PNG.to_vec(),
        }];
        let document_dir = root.join("notes");
        let staging = ImageStaging {
            document_dir: &document_dir,
            root: &root,
            requests: &requests,
        };

        for (format, ext, media_dir, text_prefix) in [
            ("docx", "docx", "word/media/", "word/document.xml"),
            ("epub", "epub", "EPUB/media/", "EPUB/text/"),
        ] {
            let out_path = out.path().join(format!("t.{ext}"));
            let options = PandocExportOptions {
                format: format.into(),
                reference_doc: None,
                extra_args: Vec::new(),
            };
            run_pandoc(
                markdown,
                out_path.to_str().unwrap(),
                "pandoc",
                &options,
                &assets,
                Some(&staging),
            )
            .unwrap_or_else(|e| panic!("{format}: {e}"));
            let file = std::fs::File::open(&out_path).unwrap();
            let mut zip = zip::ZipArchive::new(file).unwrap();
            let names: Vec<String> = (0..zip.len())
                .map(|i| zip.by_index(i).unwrap().name().to_string())
                .collect();
            let media: Vec<&String> = names.iter().filter(|n| n.starts_with(media_dir)).collect();
            // The vault image, the diagram, and the vault image again by its
            // absolute path — a separate staged copy, so a separate entry.
            assert_eq!(media.len(), 3, "{format}: {names:?}");
            // Nothing in the output holds the canary: not media, not a
            // stylesheet, not the body.
            for name in &names {
                let mut entry = zip.by_name(name).unwrap();
                let mut bytes = Vec::new();
                std::io::Read::read_to_end(&mut entry, &mut bytes).unwrap();
                assert!(
                    !bytes.windows(17).any(|w| w == b"CANARY-BYTES-9c1f"),
                    "{format}: {name} carries the file outside the vault"
                );
            }
            // The missing image became its alt text in the body.
            let mut body = String::new();
            for name in names.iter().filter(|n| n.starts_with(text_prefix)) {
                let mut entry = zip.by_name(name).unwrap();
                let mut text = String::new();
                std::io::Read::read_to_string(&mut entry, &mut text).unwrap();
                body.push_str(&text);
            }
            assert!(
                body.contains("gone"),
                "{format}: alt text of the missing image not in the body"
            );
            // The image inside the HTML block became its alt text, the refused
            // link its label, the allowed link stayed (docx keeps link targets
            // in `word/_rels/`, so every text entry is searched), the `<br>`
            // is a break.
            assert!(body.contains("indiv"), "{format}: alt of the div image");
            let mut all_text = String::new();
            for name in names.iter().filter(|n| !n.starts_with(media_dir)) {
                let mut entry = zip.by_name(name).unwrap();
                let mut text = String::new();
                if std::io::Read::read_to_string(&mut entry, &mut text).is_ok() {
                    all_text.push_str(&text);
                }
            }
            assert!(
                !all_text.contains("javascript:"),
                "{format}: refused link kept"
            );
            assert!(
                all_text.contains("example.com"),
                "{format}: allowed link lost"
            );
            let br = if format == "docx" { "<w:br" } else { "<br" };
            assert!(body.contains(br), "{format}: <br> not a line break");
            // Both staged files went in as-is; no other file from the machine did.
            for name in &media {
                let mut entry = zip.by_name(name).unwrap();
                let mut bytes = Vec::new();
                std::io::Read::read_to_end(&mut entry, &mut bytes).unwrap();
                assert_eq!(bytes, PNG, "{format}: {name}");
            }
        }
    }

    #[test]
    fn test_rewrite_asset_refs_replaces_placeholder_with_path() {
        let mut map = HashMap::new();
        map.insert(
            "mermaid-0.png".to_string(),
            "/tmp/x/mermaid-0.png".to_string(),
        );
        let md = "before ![](baram-asset:mermaid-0.png) after";
        let out = rewrite_asset_refs(md, &map);
        assert_eq!(out, "before ![](</tmp/x/mermaid-0.png>) after");
    }

    #[test]
    fn policy_filter_lists_exactly_the_bound_paths_as_lua_strings() {
        let lua = policy_filter(&["/tmp/a b/image-0.png", "C:/Users/x/it\"s.png"]);
        assert!(lua.starts_with("-- issue 545"));
        assert!(lua.contains("  [\"/tmp/a b/image-0.png\"] = true,\n"));
        assert!(lua.contains("  [\"C:/Users/x/it\\\"s.png\"] = true,\n"));
        assert!(lua.contains("Image = function(el)"));
        assert!(lua.contains("pandoc.LineBreak()"));
        assert!(lua.ends_with("}\n"));
    }

    #[test]
    fn test_rewrite_asset_refs_no_assets_is_identity() {
        let map = HashMap::new();
        let md = "no assets here";
        assert_eq!(rewrite_asset_refs(md, &map), md);
    }

    #[test]
    fn test_pandoc_asset_deserialize() {
        let json = r#"{ "name": "mermaid-0.png", "data": [137, 80, 78, 71] }"#;
        let asset: PandocAsset = serde_json::from_str(json).unwrap();
        assert_eq!(asset.name, "mermaid-0.png");
        assert_eq!(asset.data, vec![137, 80, 78, 71]);
    }

    #[test]
    fn test_rewrite_asset_refs_multiple_assets_no_prefix_clobber() {
        let mut map = HashMap::new();
        map.insert("img".to_string(), "/tmp/x/img.png".to_string());
        map.insert("img2".to_string(), "/tmp/x/img2.png".to_string());
        let md = "![](baram-asset:img) and ![](baram-asset:img2)";
        let out = rewrite_asset_refs(md, &map);
        assert_eq!(out, "![](</tmp/x/img.png>) and ![](</tmp/x/img2.png>)");
    }

    #[test]
    fn test_is_safe_asset_name() {
        assert!(is_safe_asset_name("mermaid-0.png"));
        assert!(!is_safe_asset_name(""));
        assert!(!is_safe_asset_name(".."));
        assert!(!is_safe_asset_name("../evil.png"));
        assert!(!is_safe_asset_name("a/b.png"));
        assert!(!is_safe_asset_name("a\\b.png"));
        assert!(!is_safe_asset_name("."));
        assert!(!is_safe_asset_name("a>b.png"));
        assert!(!is_safe_asset_name("a\nb.png"));
        assert!(!is_safe_asset_name("a\u{7f}b.png"));
        assert!(!is_safe_asset_name("a.png "));
        assert!(!is_safe_asset_name("a.png."));
        assert!(!is_safe_asset_name("CON"));
        assert!(!is_safe_asset_name("con.png"));
        assert!(!is_safe_asset_name("LPT1.PNG"));
        assert!(!is_safe_asset_name(INPUT_FILE_NAME));
        assert!(!is_safe_asset_name(POLICY_FILTER_NAME));
        assert!(!is_safe_asset_name("BARAM-PANDOC-INPUT.MD"));
        assert!(!is_safe_asset_name("Baram-Export-Policy.lua"));
        assert!(is_safe_asset_name("console.png"));
        // A drive prefix has no separator, and `join` would still start over
        // from it (std's `PathBuf::push` contract).
        #[cfg(windows)]
        assert!(!is_safe_asset_name("C:evil.dll"));
        #[cfg(windows)]
        assert!(!is_safe_asset_name("C:"));
    }
}
